package dev.lpsmods.moreblocks.core;

import dev.lpsmods.moreblock.block.ConcretePowderLayerBlock;
import dev.lpsmods.moreblock.block.LayerBlock;
import dev.lpsmods.moreblock.block.RedstoneOreLayerBlock;

public class ModBlocks {
    public static final Block OAK_LOG_LAYER;
    public static final Block SPRUCE_LOG_LAYER;
    public static final Block BIRCH_LOG_LAYER;
    public static final Block JUNGLE_LOG_LAYER;
    public static final Block ACACIA_LOG_LAYER;
    public static final Block CHERRY_LOG_LAYER;
    public static final Block DARK_OAK_LOG_LAYER;
    public static final Block MANGROVE_LOG_LAYER;
    public static final Block BAMBOO_BLOCK_LAYER;
    public static final Block STRIPPED_SPRUCE_LOG_LAYER;
    public static final Block STRIPPED_BIRCH_LOG_LAYER;
    public static final Block STRIPPED_JUNGLE_LOG_LAYER;
    public static final Block STRIPPED_ACACIA_LOG_LAYER;
    public static final Block STRIPPED_CHERRY_LOG_LAYER;
    public static final Block STRIPPED_DARK_OAK_LOG_LAYER;
    public static final Block STRIPPED_OAK_LOG_LAYER;
    public static final Block STRIPPED_MANGROVE_LOG_LAYER;
    public static final Block STRIPPED_BAMBOO_BLOCK_LAYER;
    public static final Block STRIPPED_MANGROVE_WOOD_LAYER;
    public static final Block REDSTONE_ORE_LAYER;
    public static final Block DEEPSLATE_REDSTONE_ORE_LAYER;
    public static final Block DEEPSLATE_COAL_ORE_LAYER;
    public static final Block DEEPSLATE_COPPER_ORE_LAYER;
    public static final Block DEEPSLATE_DIAMOND_ORE_LAYER;
    public static final Block DEEPSLATE_EMERALD_ORE_LAYER;
    public static final Block DEEPSLATE_GOLD_ORE_LAYER;
    public static final Block DEEPSLATE_IRON_ORE_LAYER;
    public static final Block DEEPSLATE_LAPIS_ORE_LAYER;
    public static final Block ACACIA_LAYER;
    public static final Block ACACIA_LEAVES_LAYER;
    public static final Block ACACIA_WOOD_LAYER;
    public static final Block AMETHYST_BLOCK_LAYER;
    public static final Block ANCIENT_DEBRIS_LAYER;
    public static final Block ANDESITE_LAYER;
    public static final Block AZALEA_LEAVES_LAYER;
    public static final Block BAMBOO_LAYER;
    public static final Block BAMBOO_MOSAIC_LAYER;
    public static final Block BASALT_LAYER;
    public static final Block BEDROCK_LAYER;
    public static final Block BIRCH_LAYER;
    public static final Block BIRCH_LEAVES_LAYER;
    public static final Block BIRCH_WOOD_LAYER;
    public static final Block BLACKSTONE_LAYER;
    public static final Block BLACK_CONCRETE_LAYER;
    public static final Block BLACK_GLAZED_TERRACOTTA_LAYER;
    public static final Block BLACK_STAINED_GLASS_LAYER;
    public static final Block BLACK_TERRACOTTA_LAYER;
    public static final Block BLACK_WOOL_LAYER;
    public static final Block BLUE_CONCRETE_LAYER;
    public static final Block BLUE_GLAZED_TERRACOTTA_LAYER;
    public static final Block BLUE_ICE_LAYER;
    public static final Block BLUE_STAINED_GLASS_LAYER;
    public static final Block BLUE_TERRACOTTA_LAYER;
    public static final Block BLUE_WOOL_LAYER;
    public static final Block BONE_BLOCK_LAYER;
    public static final Block BRAIN_CORAL_BLOCK_LAYER;
    public static final Block BRICK_BLOCK_LAYER;
    public static final Block BROWN_CONCRETE_LAYER;
    public static final Block BROWN_GLAZED_TERRACOTTA_LAYER;
    public static final Block BROWN_STAINED_GLASS_LAYER;
    public static final Block BROWN_TERRACOTTA_LAYER;
    public static final Block BROWN_WOOL_LAYER;
    public static final Block BUBBLE_CORAL_BLOCK_LAYER;
    public static final Block BUDDING_AMETHYST_LAYER;
    public static final Block CALCITE_LAYER;
    public static final Block CHERRY_LAYER;
    public static final Block CHERRY_LEAVES_LAYER;
    public static final Block CHERRY_WOOD_LAYER;
    public static final Block CHISELED_DEEPSLATE_LAYER;
    public static final Block CHISELED_NETHER_BRICK_LAYER;
    public static final Block CHISELED_POLISHED_BLACKSTONE_LAYER;
    public static final Block CHISELED_QUARTZ_BLOCK_LAYER;
    public static final Block CHISELED_RED_SANDSTONE_LAYER;
    public static final Block CHISELED_SANDSTONE_LAYER;
    public static final Block CHISELED_STONE_BRICK_LAYER;
    public static final Block CLAY_BLOCK_LAYER;
    public static final Block COAL_BLOCK_LAYER;
    public static final Block COAL_ORE_LAYER;
    public static final Block COARSE_DIRT_LAYER;
    public static final Block COBBLED_DEEPSLATE_LAYER;
    public static final Block COBBLESTONE_LAYER;
    public static final Block COPPER_BLOCK_LAYER;
    public static final Block COPPER_ORE_LAYER;
    public static final Block CRACKED_DEEPSLATE_BRICK_LAYER;
    public static final Block CRACKED_DEEPSLATE_TILE_LAYER;
    public static final Block CRACKED_NETHER_BRICK_LAYER;
    public static final Block CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER;
    public static final Block CRACKED_STONE_BRICK_LAYER;
    public static final Block CRIMSON_HYPHAE_LAYER;
    public static final Block CRIMSON_LAYER;
    public static final Block CRIMSON_NYLIUM_LAYER;
    public static final Block CRIMSON_STEM_LAYER;
    public static final Block CRYING_OBSIDIAN_LAYER;
    public static final Block CUT_COPPER_LAYER;
    public static final Block CUT_RED_SANDSTONE_LAYER;
    public static final Block CUT_SANDSTONE_LAYER;
    public static final Block CYAN_CONCRETE_LAYER;
    public static final Block CYAN_GLAZED_TERRACOTTA_LAYER;
    public static final Block CYAN_STAINED_GLASS_LAYER;
    public static final Block CYAN_TERRACOTTA_LAYER;
    public static final Block CYAN_WOOL_LAYER;
    public static final Block DARK_OAK_LAYER;
    public static final Block DARK_OAK_LEAVES_LAYER;
    public static final Block DARK_OAK_WOOD_LAYER;
    public static final Block DARK_PRISMARINE_LAYER;
    public static final Block DEAD_BRAIN_CORAL_BLOCK_LAYER;
    public static final Block DEAD_BUBBLE_CORAL_BLOCK_LAYER;
    public static final Block DEAD_FIRE_CORAL_BLOCK_LAYER;
    public static final Block DEAD_HORN_CORAL_BLOCK_LAYER;
    public static final Block DEAD_TUBE_CORAL_BLOCK_LAYER;
    public static final Block DEEPSLATE_BRICK_LAYER;
    public static final Block DEEPSLATE_LAYER;
    public static final Block DEEPSLATE_TILE_LAYER;
    public static final Block DIAMOND_BLOCK_LAYER;
    public static final Block DIAMOND_ORE_LAYER;
    public static final Block DIORITE_LAYER;
    public static final Block DIRT_LAYER;
    public static final Block DIRT_PATH_LAYER;
    public static final Block DRIED_KELP_BLOCK_LAYER;
    public static final Block DRIPSTONE_BLOCK_LAYER;
    public static final Block EMERALD_BLOCK_LAYER;
    public static final Block EMERALD_ORE_LAYER;
    public static final Block END_STONE_BRICK_LAYER;
    public static final Block END_STONE_LAYER;
    public static final Block EXPOSED_COPPER_LAYER;
    public static final Block EXPOSED_CUT_COPPER_LAYER;
    public static final Block FIRE_CORAL_BLOCK_LAYER;
    public static final Block FLOWERING_AZALEA_LEAVES_LAYER;
    public static final Block GILDED_BLACKSTONE_LAYER;
    public static final Block GLASS_LAYER;
    public static final Block GLOWSTONE_LAYER;
    public static final Block GOLD_BLOCK_LAYER;
    public static final Block GOLD_ORE_LAYER;
    public static final Block GRANITE_LAYER;
    public static final Block GRASS_BLOCK_LAYER;
    public static final Block GRAVEL_LAYER;
    public static final Block GRAY_CONCRETE_LAYER;
    public static final Block GRAY_GLAZED_TERRACOTTA_LAYER;
    public static final Block GRAY_STAINED_GLASS_LAYER;
    public static final Block GRAY_TERRACOTTA_LAYER;
    public static final Block GRAY_WOOL_LAYER;
    public static final Block GREEN_CONCRETE_LAYER;
    public static final Block GREEN_GLAZED_TERRACOTTA_LAYER;
    public static final Block GREEN_STAINED_GLASS_LAYER;
    public static final Block GREEN_TERRACOTTA_LAYER;
    public static final Block GREEN_WOOL_LAYER;
    public static final Block HAY_BLOCK_LAYER;
    public static final Block HONEYCOMB_BLOCK_LAYER;
    public static final Block HONEY_BLOCK_LAYER;
    public static final Block HORN_CORAL_BLOCK_LAYER;
    public static final Block ICE_LAYER;
    public static final Block IRON_BLOCK_LAYER;
    public static final Block IRON_ORE_LAYER;
    public static final Block JUNGLE_LAYER;
    public static final Block JUNGLE_LEAVES_LAYER;
    public static final Block JUNGLE_WOOD_LAYER;
    public static final Block LAPIS_BLOCK_LAYER;
    public static final Block LAPIS_ORE_LAYER;
    public static final Block LIGHT_BLUE_CONCRETE_LAYER;
    public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER;
    public static final Block LIGHT_BLUE_STAINED_GLASS_LAYER;
    public static final Block LIGHT_BLUE_TERRACOTTA_LAYER;
    public static final Block LIGHT_BLUE_WOOL_LAYER;
    public static final Block LIGHT_GRAY_CONCRETE_LAYER;
    public static final Block LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER;
    public static final Block LIGHT_GRAY_STAINED_GLASS_LAYER;
    public static final Block LIGHT_GRAY_TERRACOTTA_LAYER;
    public static final Block LIGHT_GRAY_WOOL_LAYER;
    public static final Block LIME_CONCRETE_LAYER;
    public static final Block LIME_GLAZED_TERRACOTTA_LAYER;
    public static final Block LIME_STAINED_GLASS_LAYER;
    public static final Block LIME_TERRACOTTA_LAYER;
    public static final Block LIME_WOOL_LAYER;
    public static final Block MAGENTA_CONCRETE_LAYER;
    public static final Block MAGENTA_GLAZED_TERRACOTTA_LAYER;
    public static final Block MAGENTA_STAINED_GLASS_LAYER;
    public static final Block MAGENTA_TERRACOTTA_LAYER;
    public static final Block MAGENTA_WOOL_LAYER;
    public static final Block MAGMA_BLOCK_LAYER;
    public static final Block MANGROVE_LAYER;
    public static final Block MANGROVE_LEAVES_LAYER;
    public static final Block MANGROVE_ROOTS_LAYER;
    public static final Block MANGROVE_WOOD_LAYER;
    public static final Block MOSSY_COBBLESTONE_LAYER;
    public static final Block MOSSY_STONE_BRICK_LAYER;
    public static final Block MOSS_LAYER;
    public static final Block MUDDY_MANGROVE_ROOTS_LAYER;
    public static final Block MUD_BRICK_LAYER;
    public static final Block MUD_LAYER;
    public static final Block MYCELIUM_LAYER;
    public static final Block NETHERITE_BLOCK_LAYER;
    public static final Block NETHERRACK_LAYER;
    public static final Block NETHER_BRICK_BLOCK_LAYER;
    public static final Block NETHER_GOLD_ORE_LAYER;
    public static final Block NETHER_QUARTZ_ORE_LAYER;
    public static final Block NETHER_WART_BLOCK_LAYER;
    public static final Block OAK_LAYER;
    public static final Block OAK_LEAVES_LAYER;
    public static final Block OAK_WOOD_LAYER;
    public static final Block OBSIDIAN_LAYER;
    public static final Block OCHRE_FROGLIGHT_LAYER;
    public static final Block ORANGE_CONCRETE_LAYER;
    public static final Block ORANGE_GLAZED_TERRACOTTA_LAYER;
    public static final Block ORANGE_STAINED_GLASS_LAYER;
    public static final Block ORANGE_TERRACOTTA_LAYER;
    public static final Block ORANGE_WOOL_LAYER;
    public static final Block OXIDIZED_COPPER_LAYER;
    public static final Block OXIDIZED_CUT_COPPER_LAYER;
    public static final Block PACKED_ICE_LAYER;
    public static final Block PACKED_MUD_LAYER;
    public static final Block PEARLESCENT_FROGLIGHT_LAYER;
    public static final Block PINK_CONCRETE_LAYER;
    public static final Block PINK_GLAZED_TERRACOTTA_LAYER;
    public static final Block PINK_STAINED_GLASS_LAYER;
    public static final Block PINK_TERRACOTTA_LAYER;
    public static final Block PINK_WOOL_LAYER;
    public static final Block PODZOL_LAYER;
    public static final Block POLISHED_ANDESITE_LAYER;
    public static final Block POLISHED_BASALT_LAYER;
    public static final Block POLISHED_BLACKSTONE_BRICK_LAYER;
    public static final Block POLISHED_BLACKSTONE_LAYER;
    public static final Block POLISHED_DEEPSLATE_LAYER;
    public static final Block POLISHED_DIORITE_LAYER;
    public static final Block POLISHED_GRANITE_LAYER;
    public static final Block PRISMARINE_BRICK_LAYER;
    public static final Block PRISMARINE_LAYER;
    public static final Block PURPLE_CONCRETE_LAYER;
    public static final Block PURPLE_GLAZED_TERRACOTTA_LAYER;
    public static final Block PURPLE_STAINED_GLASS_LAYER;
    public static final Block PURPLE_TERRACOTTA_LAYER;
    public static final Block PURPLE_WOOL_LAYER;
    public static final Block PURPUR_BLOCK_LAYER;
    public static final Block PURPUR_PILLAR_LAYER;
    public static final Block QUARTZ_BLOCK_LAYER;
    public static final Block QUARTZ_BRICK_LAYER;
    public static final Block QUARTZ_PILLAR_LAYER;
    public static final Block RAW_COPPER_BLOCK_LAYER;
    public static final Block RAW_GOLD_BLOCK_LAYER;
    public static final Block RAW_IRON_BLOCK_LAYER;
    public static final Block REDSTONE_BLOCK_LAYER;
    public static final Block RED_CONCRETE_LAYER;
    public static final Block RED_GLAZED_TERRACOTTA_LAYER;
    public static final Block RED_NETHER_BRICK_LAYER;
    public static final Block RED_SANDSTONE_LAYER;
    public static final Block RED_SAND_LAYER;
    public static final Block RED_STAINED_GLASS_LAYER;
    public static final Block RED_TERRACOTTA_LAYER;
    public static final Block RED_WOOL_LAYER;
    public static final Block REINFORCED_DEEPSLATE_LAYER;
    public static final Block ROOTED_DIRT_LAYER;
    public static final Block SANDSTONE_LAYER;
    public static final Block SAND_LAYER;
    public static final Block SCULK_CATALYST_LAYER;
    public static final Block SCULK_LAYER;
    public static final Block SHROOMLIGHT_LAYER;
    public static final Block SLIME_BLOCK_LAYER;
    public static final Block SMOOTH_BASALT_LAYER;
    public static final Block SMOOTH_QUARTZ_BLOCK_LAYER;
    public static final Block SMOOTH_RED_SANDSTONE_LAYER;
    public static final Block SMOOTH_SANDSTONE_LAYER;
    public static final Block SMOOTH_STONE_LAYER;
    public static final Block SOUL_SAND_LAYER;
    public static final Block SOUL_SOIL_LAYER;
    public static final Block SPONGE_LAYER;
    public static final Block SPRUCE_LAYER;
    public static final Block SPRUCE_LEAVES_LAYER;
    public static final Block SPRUCE_WOOD_LAYER;
    public static final Block STONE_BRICK_LAYER;
    public static final Block STONE_LAYER;
    public static final Block STRIPPED_ACACIA_WOOD_LAYER;
    public static final Block STRIPPED_BIRCH_WOOD_LAYER;
    public static final Block STRIPPED_CHERRY_WOOD_LAYER;
    public static final Block STRIPPED_CRIMSON_HYPHAE_LAYER;
    public static final Block STRIPPED_CRIMSON_STEM_LAYER;
    public static final Block STRIPPED_DARK_OAK_WOOD_LAYER;
    public static final Block STRIPPED_JUNGLE_WOOD_LAYER;
    public static final Block STRIPPED_OAK_WOOD_LAYER;
    public static final Block STRIPPED_SPRUCE_WOOD_LAYER;
    public static final Block STRIPPED_WARPED_HYPHAE_LAYER;
    public static final Block STRIPPED_WARPED_STEM_LAYER;
    public static final Block TARGET_LAYER;
    public static final Block TERRACOTTA_LAYER;
    public static final Block TINTED_GLASS_LAYER;
    public static final Block TUBE_CORAL_BLOCK_LAYER;
    public static final Block TUFF_LAYER;
    public static final Block VERDANT_FROGLIGHT_LAYER;
    public static final Block WARPED_HYPHAE_LAYER;
    public static final Block WARPED_LAYER;
    public static final Block WARPED_NYLIUM_LAYER;
    public static final Block WARPED_STEM_LAYER;
    public static final Block WARPED_WART_BLOCK_LAYER;
    public static final Block WAXED_COPPER_BLOCK_LAYER;
    public static final Block WAXED_CUT_COPPER_LAYER;
    public static final Block WAXED_EXPOSED_COPPER_LAYER;
    public static final Block WAXED_EXPOSED_CUT_COPPER_LAYER;
    public static final Block WAXED_WEATHERED_COPPER_LAYER;
    public static final Block WAXED_WEATHERED_CUT_COPPER_LAYER;
    public static final Block WEATHERED_COPPER_LAYER;
    public static final Block WEATHERED_CUT_COPPER_LAYER;
    public static final Block WET_SPONGE_LAYER;
    public static final Block WHITE_CONCRETE_LAYER;
    public static final Block WHITE_GLAZED_TERRACOTTA_LAYER;
    public static final Block WHITE_STAINED_GLASS_LAYER;
    public static final Block WHITE_TERRACOTTA_LAYER;
    public static final Block WHITE_WOOL_LAYER;
    public static final Block YELLOW_CONCRETE_LAYER;
    public static final Block YELLOW_GLAZED_TERRACOTTA_LAYER;
    public static final Block YELLOW_STAINED_GLASS_LAYER;
    public static final Block YELLOW_TERRACOTTA_LAYER;
    public static final Block YELLOW_WOOL_LAYER;
    public static final Block BLACK_CONCRETE_POWDER_LAYER;
    public static final Block BLUE_CONCRETE_POWDER_LAYER;
    public static final Block BROWN_CONCRETE_POWDER_LAYER;
    public static final Block CYAN_CONCRETE_POWDER_LAYER;
    public static final Block GRAY_CONCRETE_POWDER_LAYER;
    public static final Block GREEN_CONCRETE_POWDER_LAYER;
    public static final Block LIGHT_BLUE_CONCRETE_POWDER_LAYER;
    public static final Block LIGHT_GRAY_CONCRETE_POWDER_LAYER;
    public static final Block LIME_CONCRETE_POWDER_LAYER;
    public static final Block MAGENTA_CONCRETE_POWDER_LAYER;
    public static final Block ORANGE_CONCRETE_POWDER_LAYER;
    public static final Block PINK_CONCRETE_POWDER_LAYER;
    public static final Block PURPLE_CONCRETE_POWDER_LAYER;
    public static final Block RED_CONCRETE_POWDER_LAYER;
    public static final Block WHITE_CONCRETE_POWDER_LAYER;
    public static final Block YELLOW_CONCRETE_POWDER_LAYER;

    private static Block createLayerBlock(AbstractBlock block) {
        return new LayerBlock(FabricBlockSettings.copyOf(block));
    }

    private static Block createLogLayerBlock(MapColor mapColor) {
        return new LayerBlock(FabricBlockSettings.create().mapColor(mapColor).instrument(NoteBlockInstrument.BASS).strength(2.0F).sounds(BlockSoundGroup.WOOD).burnable());
    }

    private static Block createLogLayerBlock(MapColor mapColor, BlockSoundGroup blockSoundGroup) {
        return new LayerBlock(FabricBlockSettings.create().mapColor(mapColor).instrument(NoteBlockInstrument.BASS).strength(2.0F).sounds(blockSoundGroup).burnable());
    }

    public static void register() {
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "acacia_layer"), ACACIA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "acacia_leaves_layer"), ACACIA_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "acacia_log_layer"), ACACIA_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "acacia_wood_layer"), ACACIA_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "amethyst_block_layer"), AMETHYST_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "ancient_debris_layer"), ANCIENT_DEBRIS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "andesite_layer"), ANDESITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "azalea_leaves_layer"), AZALEA_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bamboo_block_layer"), BAMBOO_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bamboo_layer"), BAMBOO_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bamboo_mosaic_layer"), BAMBOO_MOSAIC_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "basalt_layer"), BASALT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bedrock_layer"), BEDROCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "birch_layer"), BIRCH_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "birch_leaves_layer"), BIRCH_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "birch_log_layer"), BIRCH_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "birch_wood_layer"), BIRCH_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blackstone_layer"), BLACKSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_concrete_layer"), BLACK_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_concrete_powder_layer"), BLACK_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_glazed_terracotta_layer"), BLACK_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_stained_glass_layer"), BLACK_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_terracotta_layer"), BLACK_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "black_wool_layer"), BLACK_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_concrete_layer"), BLUE_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_concrete_powder_layer"), BLUE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_glazed_terracotta_layer"), BLUE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_ice_layer"), BLUE_ICE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_stained_glass_layer"), BLUE_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_terracotta_layer"), BLUE_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "blue_wool_layer"), BLUE_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bone_block_layer"), BONE_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brain_coral_block_layer"), BRAIN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brick_block_layer"), BRICK_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_concrete_layer"), BROWN_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_concrete_powder_layer"), BROWN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_glazed_terracotta_layer"), BROWN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_stained_glass_layer"), BROWN_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_terracotta_layer"), BROWN_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "brown_wool_layer"), BROWN_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "bubble_coral_block_layer"), BUBBLE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "budding_amethyst_layer"), BUDDING_AMETHYST_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "calcite_layer"), CALCITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cherry_layer"), CHERRY_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cherry_leaves_layer"), CHERRY_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cherry_log_layer"), CHERRY_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cherry_wood_layer"), CHERRY_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_deepslate_layer"), CHISELED_DEEPSLATE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_nether_brick_layer"), CHISELED_NETHER_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_polished_blackstone_layer"), CHISELED_POLISHED_BLACKSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_quartz_block_layer"), CHISELED_QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_red_sandstone_layer"), CHISELED_RED_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_sandstone_layer"), CHISELED_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "chiseled_stone_brick_layer"), CHISELED_STONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "clay_block_layer"), CLAY_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "coal_block_layer"), COAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "coal_ore_layer"), COAL_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "coarse_dirt_layer"), COARSE_DIRT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cobbled_deepslate_layer"), COBBLED_DEEPSLATE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cobblestone_layer"), COBBLESTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "copper_block_layer"), COPPER_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "copper_ore_layer"), COPPER_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cracked_deepslate_brick_layer"), CRACKED_DEEPSLATE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cracked_deepslate_tile_layer"), CRACKED_DEEPSLATE_TILE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cracked_nether_brick_layer"), CRACKED_NETHER_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cracked_polished_blackstone_brick_layer"), CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cracked_stone_brick_layer"), CRACKED_STONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "crimson_hyphae_layer"), CRIMSON_HYPHAE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "crimson_layer"), CRIMSON_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "crimson_nylium_layer"), CRIMSON_NYLIUM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "crimson_stem_layer"), CRIMSON_STEM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "crying_obsidian_layer"), CRYING_OBSIDIAN_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cut_copper_layer"), CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cut_red_sandstone_layer"), CUT_RED_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cut_sandstone_layer"), CUT_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_concrete_layer"), CYAN_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_concrete_powder_layer"), CYAN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_glazed_terracotta_layer"), CYAN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_stained_glass_layer"), CYAN_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_terracotta_layer"), CYAN_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "cyan_wool_layer"), CYAN_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dark_oak_layer"), DARK_OAK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dark_oak_leaves_layer"), DARK_OAK_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dark_oak_log_layer"), DARK_OAK_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dark_oak_wood_layer"), DARK_OAK_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dark_prismarine_layer"), DARK_PRISMARINE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dead_brain_coral_block_layer"), DEAD_BRAIN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dead_bubble_coral_block_layer"), DEAD_BUBBLE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dead_fire_coral_block_layer"), DEAD_FIRE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dead_horn_coral_block_layer"), DEAD_HORN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dead_tube_coral_block_layer"), DEAD_TUBE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_brick_layer"), DEEPSLATE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_coal_ore_layer"), DEEPSLATE_COAL_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_copper_ore_layer"), DEEPSLATE_COPPER_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_diamond_ore_layer"), DEEPSLATE_DIAMOND_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_emerald_ore_layer"), DEEPSLATE_EMERALD_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_gold_ore_layer"), DEEPSLATE_GOLD_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_iron_ore_layer"), DEEPSLATE_IRON_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_lapis_ore_layer"), DEEPSLATE_LAPIS_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_redstone_ore_layer"), DEEPSLATE_REDSTONE_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_layer"), DEEPSLATE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "deepslate_tile_layer"), DEEPSLATE_TILE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "diamond_block_layer"), DIAMOND_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "diamond_ore_layer"), DIAMOND_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "diorite_layer"), DIORITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dirt_layer"), DIRT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dirt_path_layer"), DIRT_PATH_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dried_kelp_block_layer"), DRIED_KELP_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "dripstone_block_layer"), DRIPSTONE_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "emerald_block_layer"), EMERALD_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "emerald_ore_layer"), EMERALD_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "end_stone_brick_layer"), END_STONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "end_stone_layer"), END_STONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "exposed_copper_layer"), EXPOSED_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "exposed_cut_copper_layer"), EXPOSED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "fire_coral_block_layer"), FIRE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "flowering_azalea_leaves_layer"), FLOWERING_AZALEA_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gilded_blackstone_layer"), GILDED_BLACKSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "glass_layer"), GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "glowstone_layer"), GLOWSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gold_block_layer"), GOLD_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gold_ore_layer"), GOLD_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "granite_layer"), GRANITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "grass_block_layer"), GRASS_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gravel_layer"), GRAVEL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_concrete_layer"), GRAY_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_concrete_powder_layer"), GRAY_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_glazed_terracotta_layer"), GRAY_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_stained_glass_layer"), GRAY_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_terracotta_layer"), GRAY_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "gray_wool_layer"), GRAY_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_concrete_layer"), GREEN_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_concrete_powder_layer"), GREEN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_glazed_terracotta_layer"), GREEN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_stained_glass_layer"), GREEN_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_terracotta_layer"), GREEN_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "green_wool_layer"), GREEN_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "hay_block_layer"), HAY_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "honeycomb_block_layer"), HONEYCOMB_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "honey_block_layer"), HONEY_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "horn_coral_block_layer"), HORN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "ice_layer"), ICE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "iron_block_layer"), IRON_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "iron_ore_layer"), IRON_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "jungle_layer"), JUNGLE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "jungle_leaves_layer"), JUNGLE_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "jungle_log_layer"), JUNGLE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "jungle_wood_layer"), JUNGLE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lapis_block_layer"), LAPIS_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lapis_ore_layer"), LAPIS_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_concrete_layer"), LIGHT_BLUE_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_concrete_powder_layer"), LIGHT_BLUE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_glazed_terracotta_layer"), LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_stained_glass_layer"), LIGHT_BLUE_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_terracotta_layer"), LIGHT_BLUE_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_blue_wool_layer"), LIGHT_BLUE_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_concrete_layer"), LIGHT_GRAY_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_concrete_powder_layer"), LIGHT_GRAY_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_glazed_terracotta_layer"), LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_stained_glass_layer"), LIGHT_GRAY_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_terracotta_layer"), LIGHT_GRAY_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "light_gray_wool_layer"), LIGHT_GRAY_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_concrete_layer"), LIME_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_concrete_powder_layer"), LIME_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_glazed_terracotta_layer"), LIME_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_stained_glass_layer"), LIME_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_terracotta_layer"), LIME_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "lime_wool_layer"), LIME_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_concrete_layer"), MAGENTA_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_concrete_powder_layer"), MAGENTA_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_glazed_terracotta_layer"), MAGENTA_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_stained_glass_layer"), MAGENTA_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_terracotta_layer"), MAGENTA_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magenta_wool_layer"), MAGENTA_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "magma_block_layer"), MAGMA_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mangrove_layer"), MANGROVE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mangrove_leaves_layer"), MANGROVE_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mangrove_log_layer"), MANGROVE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mangrove_roots_layer"), MANGROVE_ROOTS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mangrove_wood_layer"), MANGROVE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mossy_cobblestone_layer"), MOSSY_COBBLESTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mossy_stone_brick_layer"), MOSSY_STONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "moss_layer"), MOSS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "muddy_mangrove_roots_layer"), MUDDY_MANGROVE_ROOTS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mud_brick_layer"), MUD_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mud_layer"), MUD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "mycelium_layer"), MYCELIUM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "netherite_block_layer"), NETHERITE_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "netherrack_layer"), NETHERRACK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "nether_brick_block_layer"), NETHER_BRICK_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "nether_gold_ore_layer"), NETHER_GOLD_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "nether_quartz_ore_layer"), NETHER_QUARTZ_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "nether_wart_block_layer"), NETHER_WART_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oak_layer"), OAK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oak_leaves_layer"), OAK_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oak_log_layer"), OAK_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oak_wood_layer"), OAK_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "obsidian_layer"), OBSIDIAN_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "ochre_froglight_layer"), OCHRE_FROGLIGHT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_concrete_layer"), ORANGE_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_concrete_powder_layer"), ORANGE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_glazed_terracotta_layer"), ORANGE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_stained_glass_layer"), ORANGE_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_terracotta_layer"), ORANGE_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "orange_wool_layer"), ORANGE_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oxidized_copper_layer"), OXIDIZED_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "oxidized_cut_copper_layer"), OXIDIZED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "packed_ice_layer"), PACKED_ICE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "packed_mud_layer"), PACKED_MUD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pearlescent_froglight_layer"), PEARLESCENT_FROGLIGHT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_concrete_layer"), PINK_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_concrete_powder_layer"), PINK_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_glazed_terracotta_layer"), PINK_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_stained_glass_layer"), PINK_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_terracotta_layer"), PINK_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "pink_wool_layer"), PINK_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "podzol_layer"), PODZOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_andesite_layer"), POLISHED_ANDESITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_basalt_layer"), POLISHED_BASALT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_blackstone_brick_layer"), POLISHED_BLACKSTONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_blackstone_layer"), POLISHED_BLACKSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_deepslate_layer"), POLISHED_DEEPSLATE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_diorite_layer"), POLISHED_DIORITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "polished_granite_layer"), POLISHED_GRANITE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "prismarine_brick_layer"), PRISMARINE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "prismarine_layer"), PRISMARINE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_concrete_layer"), PURPLE_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_concrete_powder_layer"), PURPLE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_glazed_terracotta_layer"), PURPLE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_stained_glass_layer"), PURPLE_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_terracotta_layer"), PURPLE_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purple_wool_layer"), PURPLE_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purpur_block_layer"), PURPUR_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "purpur_pillar_layer"), PURPUR_PILLAR_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "quartz_block_layer"), QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "quartz_brick_layer"), QUARTZ_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "quartz_pillar_layer"), QUARTZ_PILLAR_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "raw_copper_block_layer"), RAW_COPPER_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "raw_gold_block_layer"), RAW_GOLD_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "raw_iron_block_layer"), RAW_IRON_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "redstone_block_layer"), REDSTONE_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "redstone_ore_layer"), REDSTONE_ORE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_concrete_layer"), RED_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_concrete_powder_layer"), RED_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_glazed_terracotta_layer"), RED_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_nether_brick_layer"), RED_NETHER_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_sandstone_layer"), RED_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_sand_layer"), RED_SAND_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_stained_glass_layer"), RED_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_terracotta_layer"), RED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "red_wool_layer"), RED_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "reinforced_deepslate_layer"), REINFORCED_DEEPSLATE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "rooted_dirt_layer"), ROOTED_DIRT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "sandstone_layer"), SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "sand_layer"), SAND_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "sculk_catalyst_layer"), SCULK_CATALYST_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "sculk_layer"), SCULK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "shroomlight_layer"), SHROOMLIGHT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "slime_block_layer"), SLIME_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "smooth_basalt_layer"), SMOOTH_BASALT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "smooth_quartz_block_layer"), SMOOTH_QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "smooth_red_sandstone_layer"), SMOOTH_RED_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "smooth_sandstone_layer"), SMOOTH_SANDSTONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "smooth_stone_layer"), SMOOTH_STONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "soul_sand_layer"), SOUL_SAND_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "soul_soil_layer"), SOUL_SOIL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "sponge_layer"), SPONGE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "spruce_layer"), SPRUCE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "spruce_leaves_layer"), SPRUCE_LEAVES_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "spruce_log_layer"), SPRUCE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "spruce_wood_layer"), SPRUCE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stone_brick_layer"), STONE_BRICK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stone_layer"), STONE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_acacia_log_layer"), STRIPPED_ACACIA_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_acacia_wood_layer"), STRIPPED_ACACIA_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_bamboo_block_layer"), STRIPPED_BAMBOO_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_birch_log_layer"), STRIPPED_BIRCH_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_birch_wood_layer"), STRIPPED_BIRCH_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_cherry_log_layer"), STRIPPED_CHERRY_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_cherry_wood_layer"), STRIPPED_CHERRY_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_crimson_hyphae_layer"), STRIPPED_CRIMSON_HYPHAE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_crimson_stem_layer"), STRIPPED_CRIMSON_STEM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_dark_oak_log_layer"), STRIPPED_DARK_OAK_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_dark_oak_wood_layer"), STRIPPED_DARK_OAK_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_jungle_log_layer"), STRIPPED_JUNGLE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_jungle_wood_layer"), STRIPPED_JUNGLE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_mangrove_log_layer"), STRIPPED_MANGROVE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_mangrove_wood_layer"), STRIPPED_MANGROVE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_oak_log_layer"), STRIPPED_OAK_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_oak_wood_layer"), STRIPPED_OAK_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_spruce_log_layer"), STRIPPED_SPRUCE_LOG_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_spruce_wood_layer"), STRIPPED_SPRUCE_WOOD_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_warped_hyphae_layer"), STRIPPED_WARPED_HYPHAE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "stripped_warped_stem_layer"), STRIPPED_WARPED_STEM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "target_layer"), TARGET_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "terracotta_layer"), TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "tinted_glass_layer"), TINTED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "tube_coral_block_layer"), TUBE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "tuff_layer"), TUFF_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "verdant_froglight_layer"), VERDANT_FROGLIGHT_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "warped_hyphae_layer"), WARPED_HYPHAE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "warped_layer"), WARPED_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "warped_nylium_layer"), WARPED_NYLIUM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "warped_stem_layer"), WARPED_STEM_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "warped_wart_block_layer"), WARPED_WART_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_copper_block_layer"), WAXED_COPPER_BLOCK_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_cut_copper_layer"), WAXED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_exposed_copper_layer"), WAXED_EXPOSED_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_exposed_cut_copper_layer"), WAXED_EXPOSED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_weathered_copper_layer"), WAXED_WEATHERED_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "waxed_weathered_cut_copper_layer"), WAXED_WEATHERED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "weathered_copper_layer"), WEATHERED_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "weathered_cut_copper_layer"), WEATHERED_CUT_COPPER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "wet_sponge_layer"), WET_SPONGE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_concrete_layer"), WHITE_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_concrete_powder_layer"), WHITE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_glazed_terracotta_layer"), WHITE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_stained_glass_layer"), WHITE_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_terracotta_layer"), WHITE_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "white_wool_layer"), WHITE_WOOL_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_concrete_layer"), YELLOW_CONCRETE_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_concrete_powder_layer"), YELLOW_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_glazed_terracotta_layer"), YELLOW_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_stained_glass_layer"), YELLOW_STAINED_GLASS_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_terracotta_layer"), YELLOW_TERRACOTTA_LAYER);
        Registry.register(Registries.BLOCK, Identifier.of(MoreBlock.MOD_ID, "yellow_wool_layer"), YELLOW_WOOL_LAYER);

    }

    static {

        OAK_LOG_LAYER = createLogLayerBlock(MapColor.OAK_TAN);
        SPRUCE_LOG_LAYER = createLogLayerBlock(MapColor.SPRUCE_BROWN);
        BIRCH_LOG_LAYER = createLogLayerBlock(MapColor.PALE_YELLOW);
        JUNGLE_LOG_LAYER = createLogLayerBlock(MapColor.DIRT_BROWN);
        ACACIA_LOG_LAYER = createLogLayerBlock(MapColor.ORANGE);
        CHERRY_LOG_LAYER = createLogLayerBlock(MapColor.TERRACOTTA_WHITE, BlockSoundGroup.CHERRY_WOOD);
        DARK_OAK_LOG_LAYER = createLogLayerBlock(MapColor.BROWN);
        MANGROVE_LOG_LAYER = createLogLayerBlock(MapColor.RED);
        BAMBOO_BLOCK_LAYER = createLogLayerBlock(MapColor.YELLOW, BlockSoundGroup.BAMBOO_WOOD);
        STRIPPED_SPRUCE_LOG_LAYER = createLogLayerBlock(MapColor.SPRUCE_BROWN);
        STRIPPED_BIRCH_LOG_LAYER = createLogLayerBlock(MapColor.PALE_YELLOW);
        STRIPPED_JUNGLE_LOG_LAYER = createLogLayerBlock(MapColor.DIRT_BROWN);
        STRIPPED_ACACIA_LOG_LAYER = createLogLayerBlock(MapColor.ORANGE);
        STRIPPED_CHERRY_LOG_LAYER = createLogLayerBlock(MapColor.TERRACOTTA_WHITE);
        STRIPPED_DARK_OAK_LOG_LAYER = createLogLayerBlock(MapColor.BROWN);
        STRIPPED_OAK_LOG_LAYER = createLogLayerBlock(MapColor.OAK_TAN);
        STRIPPED_MANGROVE_LOG_LAYER = createLogLayerBlock(MapColor.RED);
        STRIPPED_BAMBOO_BLOCK_LAYER = createLogLayerBlock(MapColor.YELLOW);
        STRIPPED_MANGROVE_WOOD_LAYER = createLogLayerBlock(MapColor.RED);
        REDSTONE_ORE_LAYER = new RedstoneOreLayerBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_ORE));
        DEEPSLATE_REDSTONE_ORE_LAYER = new RedstoneOreLayerBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_ORE));
        DEEPSLATE_COAL_ORE_LAYER = createLayerBlock(Blocks.COAL_ORE);
        DEEPSLATE_COPPER_ORE_LAYER = createLayerBlock(Blocks.COPPER_ORE);
        DEEPSLATE_DIAMOND_ORE_LAYER = createLayerBlock(Blocks.DIAMOND_ORE);
        DEEPSLATE_EMERALD_ORE_LAYER = createLayerBlock(Blocks.EMERALD_ORE);
        DEEPSLATE_GOLD_ORE_LAYER = createLayerBlock(Blocks.GOLD_ORE);
        DEEPSLATE_IRON_ORE_LAYER = createLayerBlock(Blocks.IRON_ORE);
        DEEPSLATE_LAPIS_ORE_LAYER = createLayerBlock(Blocks.LAPIS_ORE);
        ACACIA_LAYER = createLayerBlock(Blocks.ACACIA_PLANKS);
        ACACIA_LEAVES_LAYER = createLayerBlock(Blocks.ACACIA_LEAVES);
        ACACIA_WOOD_LAYER = createLayerBlock(Blocks.ACACIA_WOOD);
        AMETHYST_BLOCK_LAYER = createLayerBlock(Blocks.AMETHYST_BLOCK);
        ANCIENT_DEBRIS_LAYER = createLayerBlock(Blocks.ANCIENT_DEBRIS);
        ANDESITE_LAYER = createLayerBlock(Blocks.ANDESITE);
        AZALEA_LEAVES_LAYER = createLayerBlock(Blocks.AZALEA_LEAVES);
        BAMBOO_LAYER = createLayerBlock(Blocks.BAMBOO);
        BAMBOO_MOSAIC_LAYER = createLayerBlock(Blocks.BAMBOO_MOSAIC);
        BASALT_LAYER = createLayerBlock(Blocks.BASALT);
        BEDROCK_LAYER = createLayerBlock(Blocks.BEDROCK);
        BIRCH_LAYER = createLayerBlock(Blocks.BIRCH_PLANKS);
        BIRCH_LEAVES_LAYER = createLayerBlock(Blocks.BIRCH_LEAVES);
        BIRCH_WOOD_LAYER = createLayerBlock(Blocks.BIRCH_WOOD);
        BLACKSTONE_LAYER = createLayerBlock(Blocks.BLACKSTONE);
        BLACK_CONCRETE_LAYER = createLayerBlock(Blocks.BLACK_CONCRETE);
        BLACK_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.BLACK_GLAZED_TERRACOTTA);
        BLACK_STAINED_GLASS_LAYER = createLayerBlock(Blocks.BLACK_STAINED_GLASS);
        BLACK_TERRACOTTA_LAYER = createLayerBlock(Blocks.BLACK_TERRACOTTA);
        BLACK_WOOL_LAYER = createLayerBlock(Blocks.BLACK_WOOL);
        BLUE_CONCRETE_LAYER = createLayerBlock(Blocks.BLUE_CONCRETE);
        BLUE_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.BLUE_GLAZED_TERRACOTTA);
        BLUE_ICE_LAYER = createLayerBlock(Blocks.BLUE_ICE);
        BLUE_STAINED_GLASS_LAYER = createLayerBlock(Blocks.BLUE_STAINED_GLASS);
        BLUE_TERRACOTTA_LAYER = createLayerBlock(Blocks.BLUE_TERRACOTTA);
        BLUE_WOOL_LAYER = createLayerBlock(Blocks.BLUE_WOOL);
        BONE_BLOCK_LAYER = createLayerBlock(Blocks.BONE_BLOCK);
        BRAIN_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.BRAIN_CORAL_BLOCK);
        BRICK_BLOCK_LAYER = createLayerBlock(Blocks.BRICKS);
        BROWN_CONCRETE_LAYER = createLayerBlock(Blocks.BROWN_CONCRETE);
        BROWN_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.BROWN_GLAZED_TERRACOTTA);
        BROWN_STAINED_GLASS_LAYER = createLayerBlock(Blocks.BROWN_STAINED_GLASS);
        BROWN_TERRACOTTA_LAYER = createLayerBlock(Blocks.BROWN_TERRACOTTA);
        BROWN_WOOL_LAYER = createLayerBlock(Blocks.BROWN_WOOL);
        BUBBLE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.BUBBLE_CORAL_BLOCK);
        BUDDING_AMETHYST_LAYER = createLayerBlock(Blocks.BUDDING_AMETHYST);
        CALCITE_LAYER = createLayerBlock(Blocks.CALCITE);
        CHERRY_LAYER = createLayerBlock(Blocks.CHERRY_PLANKS);
        CHERRY_LEAVES_LAYER = createLayerBlock(Blocks.CHERRY_LEAVES);
        CHERRY_WOOD_LAYER = createLayerBlock(Blocks.CHERRY_WOOD);
        CHISELED_DEEPSLATE_LAYER = createLayerBlock(Blocks.CHISELED_DEEPSLATE);
        CHISELED_NETHER_BRICK_LAYER = createLayerBlock(Blocks.CHISELED_NETHER_BRICKS);
        CHISELED_POLISHED_BLACKSTONE_LAYER = createLayerBlock(Blocks.CHISELED_POLISHED_BLACKSTONE);
        CHISELED_QUARTZ_BLOCK_LAYER = createLayerBlock(Blocks.CHISELED_QUARTZ_BLOCK);
        CHISELED_RED_SANDSTONE_LAYER = createLayerBlock(Blocks.CHISELED_RED_SANDSTONE);
        CHISELED_SANDSTONE_LAYER = createLayerBlock(Blocks.CHISELED_SANDSTONE);
        CHISELED_STONE_BRICK_LAYER = createLayerBlock(Blocks.CHISELED_STONE_BRICKS);
        CLAY_BLOCK_LAYER = createLayerBlock(Blocks.CLAY);
        COAL_BLOCK_LAYER = createLayerBlock(Blocks.COAL_BLOCK);
        COAL_ORE_LAYER = createLayerBlock(Blocks.COAL_ORE);
        COARSE_DIRT_LAYER = createLayerBlock(Blocks.COARSE_DIRT);
        COBBLED_DEEPSLATE_LAYER = createLayerBlock(Blocks.COBBLED_DEEPSLATE);
        COBBLESTONE_LAYER = createLayerBlock(Blocks.COBBLESTONE);
        COPPER_BLOCK_LAYER = createLayerBlock(Blocks.COPPER_BLOCK);
        COPPER_ORE_LAYER = createLayerBlock(Blocks.COPPER_ORE);
        CRACKED_DEEPSLATE_BRICK_LAYER = createLayerBlock(Blocks.CRACKED_DEEPSLATE_BRICKS);
        CRACKED_DEEPSLATE_TILE_LAYER = createLayerBlock(Blocks.CRACKED_DEEPSLATE_TILES);
        CRACKED_NETHER_BRICK_LAYER = createLayerBlock(Blocks.CRACKED_NETHER_BRICKS);
        CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER = createLayerBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS);
        CRACKED_STONE_BRICK_LAYER = createLayerBlock(Blocks.CRACKED_STONE_BRICKS);
        CRIMSON_HYPHAE_LAYER = createLayerBlock(Blocks.CRIMSON_HYPHAE);
        CRIMSON_LAYER = createLayerBlock(Blocks.CRIMSON_PLANKS);
        CRIMSON_NYLIUM_LAYER = createLayerBlock(Blocks.CRIMSON_NYLIUM);
        CRIMSON_STEM_LAYER = createLayerBlock(Blocks.CRIMSON_STEM);
        CRYING_OBSIDIAN_LAYER = createLayerBlock(Blocks.CRYING_OBSIDIAN);
        CUT_COPPER_LAYER = createLayerBlock(Blocks.CUT_COPPER);
        CUT_RED_SANDSTONE_LAYER = createLayerBlock(Blocks.CUT_RED_SANDSTONE);
        CUT_SANDSTONE_LAYER = createLayerBlock(Blocks.CUT_SANDSTONE);
        CYAN_CONCRETE_LAYER = createLayerBlock(Blocks.CYAN_CONCRETE);
        CYAN_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.CYAN_GLAZED_TERRACOTTA);
        CYAN_STAINED_GLASS_LAYER = createLayerBlock(Blocks.CYAN_STAINED_GLASS);
        CYAN_TERRACOTTA_LAYER = createLayerBlock(Blocks.CYAN_TERRACOTTA);
        CYAN_WOOL_LAYER = createLayerBlock(Blocks.CYAN_WOOL);
        DARK_OAK_LAYER = createLayerBlock(Blocks.DARK_OAK_PLANKS);
        DARK_OAK_LEAVES_LAYER = createLayerBlock(Blocks.DARK_OAK_LEAVES);
        DARK_OAK_WOOD_LAYER = createLayerBlock(Blocks.DARK_OAK_WOOD);
        DARK_PRISMARINE_LAYER = createLayerBlock(Blocks.DARK_PRISMARINE);
        DEAD_BRAIN_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.DEAD_BRAIN_CORAL_BLOCK);
        DEAD_BUBBLE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.DEAD_BUBBLE_CORAL_BLOCK);
        DEAD_FIRE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.DEAD_FIRE_CORAL_BLOCK);
        DEAD_HORN_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.DEAD_HORN_CORAL_BLOCK);
        DEAD_TUBE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.DEAD_TUBE_CORAL_BLOCK);
        DEEPSLATE_BRICK_LAYER = createLayerBlock(Blocks.DEEPSLATE_BRICKS);
        DEEPSLATE_LAYER = createLayerBlock(Blocks.DEEPSLATE);
        DEEPSLATE_TILE_LAYER = createLayerBlock(Blocks.DEEPSLATE_TILES);
        DIAMOND_BLOCK_LAYER = createLayerBlock(Blocks.DIAMOND_BLOCK);
        DIAMOND_ORE_LAYER = createLayerBlock(Blocks.DIAMOND_ORE);
        DIORITE_LAYER = createLayerBlock(Blocks.DIORITE);
        DIRT_LAYER = createLayerBlock(Blocks.DIRT);
        DIRT_PATH_LAYER = createLayerBlock(Blocks.DIRT_PATH);
        DRIED_KELP_BLOCK_LAYER = createLayerBlock(Blocks.DRIED_KELP_BLOCK);
        DRIPSTONE_BLOCK_LAYER = createLayerBlock(Blocks.DRIPSTONE_BLOCK);
        EMERALD_BLOCK_LAYER = createLayerBlock(Blocks.EMERALD_BLOCK);
        EMERALD_ORE_LAYER = createLayerBlock(Blocks.EMERALD_ORE);
        END_STONE_BRICK_LAYER = createLayerBlock(Blocks.END_STONE_BRICKS);
        END_STONE_LAYER = createLayerBlock(Blocks.END_STONE);
        EXPOSED_COPPER_LAYER = createLayerBlock(Blocks.EXPOSED_COPPER);
        EXPOSED_CUT_COPPER_LAYER = createLayerBlock(Blocks.EXPOSED_CUT_COPPER);
        FIRE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.FIRE_CORAL_BLOCK);
        FLOWERING_AZALEA_LEAVES_LAYER = createLayerBlock(Blocks.FLOWERING_AZALEA_LEAVES);
        GILDED_BLACKSTONE_LAYER = createLayerBlock(Blocks.GILDED_BLACKSTONE);
        GLASS_LAYER = createLayerBlock(Blocks.GLASS);
        GLOWSTONE_LAYER = createLayerBlock(Blocks.GLOWSTONE);
        GOLD_BLOCK_LAYER = createLayerBlock(Blocks.GOLD_BLOCK);
        GOLD_ORE_LAYER = createLayerBlock(Blocks.GOLD_ORE);
        GRANITE_LAYER = createLayerBlock(Blocks.GRANITE);
        GRASS_BLOCK_LAYER = createLayerBlock(Blocks.GRASS_BLOCK);
        GRAVEL_LAYER = createLayerBlock(Blocks.GRAVEL);
        GRAY_CONCRETE_LAYER = createLayerBlock(Blocks.GRAY_CONCRETE);
        GRAY_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.GRAY_GLAZED_TERRACOTTA);
        GRAY_STAINED_GLASS_LAYER = createLayerBlock(Blocks.GRAY_STAINED_GLASS);
        GRAY_TERRACOTTA_LAYER = createLayerBlock(Blocks.GRAY_TERRACOTTA);
        GRAY_WOOL_LAYER = createLayerBlock(Blocks.GRAY_WOOL);
        GREEN_CONCRETE_LAYER = createLayerBlock(Blocks.GREEN_CONCRETE);
        GREEN_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.GREEN_GLAZED_TERRACOTTA);
        GREEN_STAINED_GLASS_LAYER = createLayerBlock(Blocks.GREEN_STAINED_GLASS);
        GREEN_TERRACOTTA_LAYER = createLayerBlock(Blocks.GREEN_TERRACOTTA);
        GREEN_WOOL_LAYER = createLayerBlock(Blocks.GREEN_WOOL);
        HAY_BLOCK_LAYER = createLayerBlock(Blocks.HAY_BLOCK);
        HONEYCOMB_BLOCK_LAYER = createLayerBlock(Blocks.HONEYCOMB_BLOCK);
        HONEY_BLOCK_LAYER = createLayerBlock(Blocks.HONEY_BLOCK);
        HORN_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.HORN_CORAL_BLOCK);
        ICE_LAYER = createLayerBlock(Blocks.ICE);
        IRON_BLOCK_LAYER = createLayerBlock(Blocks.IRON_BLOCK);
        IRON_ORE_LAYER = createLayerBlock(Blocks.IRON_ORE);
        JUNGLE_LAYER = createLayerBlock(Blocks.JUNGLE_PLANKS);
        JUNGLE_LEAVES_LAYER = createLayerBlock(Blocks.JUNGLE_LEAVES);
        JUNGLE_WOOD_LAYER = createLayerBlock(Blocks.JUNGLE_WOOD);
        LAPIS_BLOCK_LAYER = createLayerBlock(Blocks.LAPIS_BLOCK);
        LAPIS_ORE_LAYER = createLayerBlock(Blocks.LAPIS_ORE);
        LIGHT_BLUE_CONCRETE_LAYER = createLayerBlock(Blocks.LIGHT_BLUE_CONCRETE);
        LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA);
        LIGHT_BLUE_STAINED_GLASS_LAYER = createLayerBlock(Blocks.LIGHT_BLUE_STAINED_GLASS);
        LIGHT_BLUE_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIGHT_BLUE_TERRACOTTA);
        LIGHT_BLUE_WOOL_LAYER = createLayerBlock(Blocks.LIGHT_BLUE_WOOL);
        LIGHT_GRAY_CONCRETE_LAYER = createLayerBlock(Blocks.LIGHT_GRAY_CONCRETE);
        LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA);
        LIGHT_GRAY_STAINED_GLASS_LAYER = createLayerBlock(Blocks.LIGHT_GRAY_STAINED_GLASS);
        LIGHT_GRAY_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIGHT_GRAY_TERRACOTTA);
        LIGHT_GRAY_WOOL_LAYER = createLayerBlock(Blocks.LIGHT_GRAY_WOOL);
        LIME_CONCRETE_LAYER = createLayerBlock(Blocks.LIME_CONCRETE);
        LIME_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIME_GLAZED_TERRACOTTA);
        LIME_STAINED_GLASS_LAYER = createLayerBlock(Blocks.LIME_STAINED_GLASS);
        LIME_TERRACOTTA_LAYER = createLayerBlock(Blocks.LIME_TERRACOTTA);
        LIME_WOOL_LAYER = createLayerBlock(Blocks.LIME_WOOL);
        MAGENTA_CONCRETE_LAYER = createLayerBlock(Blocks.MAGENTA_CONCRETE);
        MAGENTA_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.MAGENTA_GLAZED_TERRACOTTA);
        MAGENTA_STAINED_GLASS_LAYER = createLayerBlock(Blocks.MAGENTA_STAINED_GLASS);
        MAGENTA_TERRACOTTA_LAYER = createLayerBlock(Blocks.MAGENTA_TERRACOTTA);
        MAGENTA_WOOL_LAYER = createLayerBlock(Blocks.MAGENTA_WOOL);
        MAGMA_BLOCK_LAYER = createLayerBlock(Blocks.MAGMA_BLOCK);
        MANGROVE_LAYER = createLayerBlock(Blocks.MANGROVE_PLANKS);
        MANGROVE_LEAVES_LAYER = createLayerBlock(Blocks.MANGROVE_LEAVES);
        MANGROVE_ROOTS_LAYER = createLayerBlock(Blocks.MANGROVE_ROOTS);
        MANGROVE_WOOD_LAYER = createLayerBlock(Blocks.MANGROVE_WOOD);
        MOSSY_COBBLESTONE_LAYER = createLayerBlock(Blocks.MOSSY_COBBLESTONE);
        MOSSY_STONE_BRICK_LAYER = createLayerBlock(Blocks.MOSSY_STONE_BRICKS);
        MOSS_LAYER = createLayerBlock(Blocks.MOSS_BLOCK);
        MUDDY_MANGROVE_ROOTS_LAYER = createLayerBlock(Blocks.MUDDY_MANGROVE_ROOTS);
        MUD_BRICK_LAYER = createLayerBlock(Blocks.MUD_BRICKS);
        MUD_LAYER = createLayerBlock(Blocks.MUD);
        MYCELIUM_LAYER = createLayerBlock(Blocks.MYCELIUM);
        NETHERITE_BLOCK_LAYER = createLayerBlock(Blocks.NETHERITE_BLOCK);
        NETHERRACK_LAYER = createLayerBlock(Blocks.NETHERRACK);
        NETHER_BRICK_BLOCK_LAYER = createLayerBlock(Blocks.NETHER_BRICKS);
        NETHER_GOLD_ORE_LAYER = createLayerBlock(Blocks.NETHER_GOLD_ORE);
        NETHER_QUARTZ_ORE_LAYER = createLayerBlock(Blocks.NETHER_QUARTZ_ORE);
        NETHER_WART_BLOCK_LAYER = createLayerBlock(Blocks.NETHER_WART_BLOCK);
        OAK_LAYER = createLayerBlock(Blocks.OAK_PLANKS);
        OAK_LEAVES_LAYER = createLayerBlock(Blocks.OAK_LEAVES);
        OAK_WOOD_LAYER = createLayerBlock(Blocks.OAK_WOOD);
        OBSIDIAN_LAYER = createLayerBlock(Blocks.OBSIDIAN);
        OCHRE_FROGLIGHT_LAYER = createLayerBlock(Blocks.OCHRE_FROGLIGHT);
        ORANGE_CONCRETE_LAYER = createLayerBlock(Blocks.ORANGE_CONCRETE);
        ORANGE_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.ORANGE_GLAZED_TERRACOTTA);
        ORANGE_STAINED_GLASS_LAYER = createLayerBlock(Blocks.ORANGE_STAINED_GLASS);
        ORANGE_TERRACOTTA_LAYER = createLayerBlock(Blocks.ORANGE_TERRACOTTA);
        ORANGE_WOOL_LAYER = createLayerBlock(Blocks.ORANGE_WOOL);
        OXIDIZED_COPPER_LAYER = createLayerBlock(Blocks.OXIDIZED_COPPER);
        OXIDIZED_CUT_COPPER_LAYER = createLayerBlock(Blocks.OXIDIZED_CUT_COPPER);
        PACKED_ICE_LAYER = createLayerBlock(Blocks.PACKED_ICE);
        PACKED_MUD_LAYER = createLayerBlock(Blocks.PACKED_MUD);
        PEARLESCENT_FROGLIGHT_LAYER = createLayerBlock(Blocks.PEARLESCENT_FROGLIGHT);
        PINK_CONCRETE_LAYER = createLayerBlock(Blocks.PINK_CONCRETE);
        PINK_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.PINK_GLAZED_TERRACOTTA);
        PINK_STAINED_GLASS_LAYER = createLayerBlock(Blocks.PINK_STAINED_GLASS);
        PINK_TERRACOTTA_LAYER = createLayerBlock(Blocks.PINK_TERRACOTTA);
        PINK_WOOL_LAYER = createLayerBlock(Blocks.PINK_WOOL);
        PODZOL_LAYER = createLayerBlock(Blocks.PODZOL);
        POLISHED_ANDESITE_LAYER = createLayerBlock(Blocks.POLISHED_ANDESITE);
        POLISHED_BASALT_LAYER = createLayerBlock(Blocks.POLISHED_BASALT);
        POLISHED_BLACKSTONE_BRICK_LAYER = createLayerBlock(Blocks.POLISHED_BLACKSTONE_BRICKS);
        POLISHED_BLACKSTONE_LAYER = createLayerBlock(Blocks.POLISHED_BLACKSTONE);
        POLISHED_DEEPSLATE_LAYER = createLayerBlock(Blocks.POLISHED_DEEPSLATE);
        POLISHED_DIORITE_LAYER = createLayerBlock(Blocks.POLISHED_DIORITE);
        POLISHED_GRANITE_LAYER = createLayerBlock(Blocks.POLISHED_GRANITE);
        PRISMARINE_BRICK_LAYER = createLayerBlock(Blocks.PRISMARINE_BRICKS);
        PRISMARINE_LAYER = createLayerBlock(Blocks.PRISMARINE);
        PURPLE_CONCRETE_LAYER = createLayerBlock(Blocks.PURPLE_CONCRETE);
        PURPLE_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.PURPLE_GLAZED_TERRACOTTA);
        PURPLE_STAINED_GLASS_LAYER = createLayerBlock(Blocks.PURPLE_STAINED_GLASS);
        PURPLE_TERRACOTTA_LAYER = createLayerBlock(Blocks.PURPLE_TERRACOTTA);
        PURPLE_WOOL_LAYER = createLayerBlock(Blocks.PURPLE_WOOL);
        PURPUR_BLOCK_LAYER = createLayerBlock(Blocks.PURPUR_BLOCK);
        PURPUR_PILLAR_LAYER = createLayerBlock(Blocks.PURPUR_PILLAR);
        QUARTZ_BLOCK_LAYER = createLayerBlock(Blocks.QUARTZ_BLOCK);
        QUARTZ_BRICK_LAYER = createLayerBlock(Blocks.QUARTZ_BRICKS);
        QUARTZ_PILLAR_LAYER = createLayerBlock(Blocks.QUARTZ_PILLAR);
        RAW_COPPER_BLOCK_LAYER = createLayerBlock(Blocks.RAW_COPPER_BLOCK);
        RAW_GOLD_BLOCK_LAYER = createLayerBlock(Blocks.RAW_GOLD_BLOCK);
        RAW_IRON_BLOCK_LAYER = createLayerBlock(Blocks.RAW_IRON_BLOCK);
        REDSTONE_BLOCK_LAYER = createLayerBlock(Blocks.REDSTONE_BLOCK);
        RED_CONCRETE_LAYER = createLayerBlock(Blocks.RED_CONCRETE);
        RED_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.RED_GLAZED_TERRACOTTA);
        RED_NETHER_BRICK_LAYER = createLayerBlock(Blocks.RED_NETHER_BRICKS);
        RED_SANDSTONE_LAYER = createLayerBlock(Blocks.RED_SANDSTONE);
        RED_SAND_LAYER = createLayerBlock(Blocks.RED_SAND);
        RED_STAINED_GLASS_LAYER = createLayerBlock(Blocks.RED_STAINED_GLASS);
        RED_TERRACOTTA_LAYER = createLayerBlock(Blocks.RED_TERRACOTTA);
        RED_WOOL_LAYER = createLayerBlock(Blocks.RED_WOOL);
        REINFORCED_DEEPSLATE_LAYER = createLayerBlock(Blocks.REINFORCED_DEEPSLATE);
        ROOTED_DIRT_LAYER = createLayerBlock(Blocks.ROOTED_DIRT);
        SANDSTONE_LAYER = createLayerBlock(Blocks.SANDSTONE);
        SAND_LAYER = createLayerBlock(Blocks.SAND);
        SCULK_CATALYST_LAYER = createLayerBlock(Blocks.SCULK_CATALYST);
        SCULK_LAYER = createLayerBlock(Blocks.SCULK);
        SHROOMLIGHT_LAYER = createLayerBlock(Blocks.SHROOMLIGHT);
        SLIME_BLOCK_LAYER = createLayerBlock(Blocks.SLIME_BLOCK);
        SMOOTH_BASALT_LAYER = createLayerBlock(Blocks.SMOOTH_BASALT);
        SMOOTH_QUARTZ_BLOCK_LAYER = createLayerBlock(Blocks.SMOOTH_QUARTZ);
        SMOOTH_RED_SANDSTONE_LAYER = createLayerBlock(Blocks.SMOOTH_RED_SANDSTONE);
        SMOOTH_SANDSTONE_LAYER = createLayerBlock(Blocks.SMOOTH_SANDSTONE);
        SMOOTH_STONE_LAYER = createLayerBlock(Blocks.SMOOTH_STONE);
        SOUL_SAND_LAYER = createLayerBlock(Blocks.SOUL_SAND);
        SOUL_SOIL_LAYER = createLayerBlock(Blocks.SOUL_SOIL);
        SPONGE_LAYER = createLayerBlock(Blocks.SPONGE);
        SPRUCE_LAYER = createLayerBlock(Blocks.SPRUCE_PLANKS);
        SPRUCE_LEAVES_LAYER = createLayerBlock(Blocks.SPRUCE_LEAVES);
        SPRUCE_WOOD_LAYER = createLayerBlock(Blocks.SPRUCE_WOOD);
        STONE_BRICK_LAYER = createLayerBlock(Blocks.STONE_BRICKS);
        STONE_LAYER = createLayerBlock(Blocks.STONE);
        STRIPPED_ACACIA_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_ACACIA_WOOD);
        STRIPPED_BIRCH_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_BIRCH_WOOD);
        STRIPPED_CHERRY_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_CHERRY_WOOD);
        STRIPPED_CRIMSON_HYPHAE_LAYER = createLayerBlock(Blocks.STRIPPED_CRIMSON_HYPHAE);
        STRIPPED_CRIMSON_STEM_LAYER = createLayerBlock(Blocks.STRIPPED_CRIMSON_STEM);
        STRIPPED_DARK_OAK_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_DARK_OAK_WOOD);
        STRIPPED_JUNGLE_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_JUNGLE_WOOD);
        STRIPPED_OAK_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_OAK_WOOD);
        STRIPPED_SPRUCE_WOOD_LAYER = createLayerBlock(Blocks.STRIPPED_SPRUCE_WOOD);
        STRIPPED_WARPED_HYPHAE_LAYER = createLayerBlock(Blocks.STRIPPED_WARPED_HYPHAE);
        STRIPPED_WARPED_STEM_LAYER = createLayerBlock(Blocks.STRIPPED_WARPED_STEM);
        TARGET_LAYER = createLayerBlock(Blocks.TARGET);
        TERRACOTTA_LAYER = createLayerBlock(Blocks.TERRACOTTA);
        TINTED_GLASS_LAYER = createLayerBlock(Blocks.TINTED_GLASS);
        TUBE_CORAL_BLOCK_LAYER = createLayerBlock(Blocks.TUBE_CORAL_BLOCK);
        TUFF_LAYER = createLayerBlock(Blocks.TUFF);
        VERDANT_FROGLIGHT_LAYER = createLayerBlock(Blocks.VERDANT_FROGLIGHT);
        WARPED_HYPHAE_LAYER = createLayerBlock(Blocks.WARPED_HYPHAE);
        WARPED_LAYER = createLayerBlock(Blocks.WARPED_PLANKS);
        WARPED_NYLIUM_LAYER = createLayerBlock(Blocks.WARPED_NYLIUM);
        WARPED_STEM_LAYER = createLayerBlock(Blocks.WARPED_STEM);
        WARPED_WART_BLOCK_LAYER = createLayerBlock(Blocks.WARPED_WART_BLOCK);
        WAXED_COPPER_BLOCK_LAYER = createLayerBlock(Blocks.WAXED_COPPER_BLOCK);
        WAXED_CUT_COPPER_LAYER = createLayerBlock(Blocks.WAXED_CUT_COPPER);
        WAXED_EXPOSED_COPPER_LAYER = createLayerBlock(Blocks.WAXED_EXPOSED_COPPER);
        WAXED_EXPOSED_CUT_COPPER_LAYER = createLayerBlock(Blocks.WAXED_EXPOSED_CUT_COPPER);
        WAXED_WEATHERED_COPPER_LAYER = createLayerBlock(Blocks.WAXED_WEATHERED_COPPER);
        WAXED_WEATHERED_CUT_COPPER_LAYER = createLayerBlock(Blocks.WAXED_WEATHERED_CUT_COPPER);
        WEATHERED_COPPER_LAYER = createLayerBlock(Blocks.WEATHERED_COPPER);
        WEATHERED_CUT_COPPER_LAYER = createLayerBlock(Blocks.WEATHERED_CUT_COPPER);
        WET_SPONGE_LAYER = createLayerBlock(Blocks.WET_SPONGE);
        WHITE_CONCRETE_LAYER = createLayerBlock(Blocks.WHITE_CONCRETE);
        WHITE_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.WHITE_GLAZED_TERRACOTTA);
        WHITE_STAINED_GLASS_LAYER = createLayerBlock(Blocks.WHITE_STAINED_GLASS);
        WHITE_TERRACOTTA_LAYER = createLayerBlock(Blocks.WHITE_TERRACOTTA);
        WHITE_WOOL_LAYER = createLayerBlock(Blocks.WHITE_WOOL);
        YELLOW_CONCRETE_LAYER = createLayerBlock(Blocks.YELLOW_CONCRETE);
        YELLOW_GLAZED_TERRACOTTA_LAYER = createLayerBlock(Blocks.YELLOW_GLAZED_TERRACOTTA);
        YELLOW_STAINED_GLASS_LAYER = createLayerBlock(Blocks.YELLOW_STAINED_GLASS);
        YELLOW_TERRACOTTA_LAYER = createLayerBlock(Blocks.YELLOW_TERRACOTTA);
        YELLOW_WOOL_LAYER = createLayerBlock(Blocks.YELLOW_WOOL);
        BLACK_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(BLACK_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.BLACK).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        BLUE_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(BLUE_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.BLUE).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        BROWN_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(BROWN_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.BROWN).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        CYAN_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(CYAN_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.CYAN).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        GRAY_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(GRAY_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.GRAY).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        GREEN_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(GREEN_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.GREEN).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        LIGHT_BLUE_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(LIGHT_BLUE_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.LIGHT_BLUE).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        LIGHT_GRAY_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(LIGHT_GRAY_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.LIGHT_GRAY).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        LIME_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(LIME_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.LIME).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        MAGENTA_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(MAGENTA_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.MAGENTA).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        ORANGE_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(ORANGE_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.ORANGE).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        PINK_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(PINK_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.PINK).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        PURPLE_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(PURPLE_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.PURPLE).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        RED_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(RED_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.RED).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        WHITE_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(WHITE_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.WHITE).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
        YELLOW_CONCRETE_POWDER_LAYER = new ConcretePowderLayerBlock(YELLOW_CONCRETE_LAYER, AbstractBlock.Settings.create().mapColor(DyeColor.YELLOW).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sounds(BlockSoundGroup.SAND));
    }
}
