package dev.lpsmods.moreblocks.core;

public class ModItems {
    public static final Item ACACIA_LAYER;
    public static final Item ACACIA_LEAVES_LAYER;
    public static final Item ACACIA_LOG_LAYER;
    public static final Item ACACIA_WOOD_LAYER;
    public static final Item AMETHYST_BLOCK_LAYER;
    public static final Item ANCIENT_DEBRIS_LAYER;
    public static final Item ANDESITE_LAYER;
    public static final Item AZALEA_LEAVES_LAYER;
    public static final Item BAMBOO_BLOCK_LAYER;
    public static final Item BAMBOO_LAYER;
    public static final Item BAMBOO_MOSAIC_LAYER;
    public static final Item BASALT_LAYER;
    public static final Item BEDROCK_LAYER;
    public static final Item BIRCH_LAYER;
    public static final Item BIRCH_LEAVES_LAYER;
    public static final Item BIRCH_LOG_LAYER;
    public static final Item BIRCH_WOOD_LAYER;
    public static final Item BLACKSTONE_LAYER;
    public static final Item BLACK_CONCRETE_LAYER;
    public static final Item BLACK_CONCRETE_POWDER_LAYER;
    public static final Item BLACK_GLAZED_TERRACOTTA_LAYER;
    public static final Item BLACK_STAINED_GLASS_LAYER;
    public static final Item BLACK_TERRACOTTA_LAYER;
    public static final Item BLACK_WOOL_LAYER;
    public static final Item BLUE_CONCRETE_LAYER;
    public static final Item BLUE_CONCRETE_POWDER_LAYER;
    public static final Item BLUE_GLAZED_TERRACOTTA_LAYER;
    public static final Item BLUE_ICE_LAYER;
    public static final Item BLUE_STAINED_GLASS_LAYER;
    public static final Item BLUE_TERRACOTTA_LAYER;
    public static final Item BLUE_WOOL_LAYER;
    public static final Item BONE_BLOCK_LAYER;
    public static final Item BRAIN_CORAL_BLOCK_LAYER;
    public static final Item BRICK_BLOCK_LAYER;
    public static final Item BROWN_CONCRETE_LAYER;
    public static final Item BROWN_CONCRETE_POWDER_LAYER;
    public static final Item BROWN_GLAZED_TERRACOTTA_LAYER;
    public static final Item BROWN_STAINED_GLASS_LAYER;
    public static final Item BROWN_TERRACOTTA_LAYER;
    public static final Item BROWN_WOOL_LAYER;
    public static final Item BUBBLE_CORAL_BLOCK_LAYER;
    public static final Item BUDDING_AMETHYST_LAYER;
    public static final Item CALCITE_LAYER;
    public static final Item CHERRY_LAYER;
    public static final Item CHERRY_LEAVES_LAYER;
    public static final Item CHERRY_LOG_LAYER;
    public static final Item CHERRY_WOOD_LAYER;
    public static final Item CHISELED_DEEPSLATE_LAYER;
    public static final Item CHISELED_NETHER_BRICK_LAYER;
    public static final Item CHISELED_POLISHED_BLACKSTONE_LAYER;
    public static final Item CHISELED_QUARTZ_BLOCK_LAYER;
    public static final Item CHISELED_RED_SANDSTONE_LAYER;
    public static final Item CHISELED_SANDSTONE_LAYER;
    public static final Item CHISELED_STONE_BRICK_LAYER;
    public static final Item CLAY_BLOCK_LAYER;
    public static final Item COAL_BLOCK_LAYER;
    public static final Item COAL_ORE_LAYER;
    public static final Item COARSE_DIRT_LAYER;
    public static final Item COBBLED_DEEPSLATE_LAYER;
    public static final Item COBBLESTONE_LAYER;
    public static final Item COPPER_BLOCK_LAYER;
    public static final Item COPPER_ORE_LAYER;
    public static final Item CRACKED_DEEPSLATE_BRICK_LAYER;
    public static final Item CRACKED_DEEPSLATE_TILE_LAYER;
    public static final Item CRACKED_NETHER_BRICK_LAYER;
    public static final Item CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER;
    public static final Item CRACKED_STONE_BRICK_LAYER;
    public static final Item CRIMSON_HYPHAE_LAYER;
    public static final Item CRIMSON_LAYER;
    public static final Item CRIMSON_NYLIUM_LAYER;
    public static final Item CRIMSON_STEM_LAYER;
    public static final Item CRYING_OBSIDIAN_LAYER;
    public static final Item CUT_COPPER_LAYER;
    public static final Item CUT_RED_SANDSTONE_LAYER;
    public static final Item CUT_SANDSTONE_LAYER;
    public static final Item CYAN_CONCRETE_LAYER;
    public static final Item CYAN_CONCRETE_POWDER_LAYER;
    public static final Item CYAN_GLAZED_TERRACOTTA_LAYER;
    public static final Item CYAN_STAINED_GLASS_LAYER;
    public static final Item CYAN_TERRACOTTA_LAYER;
    public static final Item CYAN_WOOL_LAYER;
    public static final Item DARK_OAK_LAYER;
    public static final Item DARK_OAK_LEAVES_LAYER;
    public static final Item DARK_OAK_LOG_LAYER;
    public static final Item DARK_OAK_WOOD_LAYER;
    public static final Item DARK_PRISMARINE_LAYER;
    public static final Item DEAD_BRAIN_CORAL_BLOCK_LAYER;
    public static final Item DEAD_BUBBLE_CORAL_BLOCK_LAYER;
    public static final Item DEAD_FIRE_CORAL_BLOCK_LAYER;
    public static final Item DEAD_HORN_CORAL_BLOCK_LAYER;
    public static final Item DEAD_TUBE_CORAL_BLOCK_LAYER;
    public static final Item DEEPSLATE_BRICK_LAYER;
    public static final Item DEEPSLATE_COAL_ORE_LAYER;
    public static final Item DEEPSLATE_COPPER_ORE_LAYER;
    public static final Item DEEPSLATE_DIAMOND_ORE_LAYER;
    public static final Item DEEPSLATE_EMERALD_ORE_LAYER;
    public static final Item DEEPSLATE_GOLD_ORE_LAYER;
    public static final Item DEEPSLATE_IRON_ORE_LAYER;
    public static final Item DEEPSLATE_LAPIS_ORE_LAYER;
    public static final Item DEEPSLATE_LAYER;
    public static final Item DEEPSLATE_REDSTONE_ORE_LAYER;
    public static final Item DEEPSLATE_TILE_LAYER;
    public static final Item DIAMOND_BLOCK_LAYER;
    public static final Item DIAMOND_ORE_LAYER;
    public static final Item DIORITE_LAYER;
    public static final Item DIRT_LAYER;
    public static final Item DIRT_PATH_LAYER;
    public static final Item DRIED_KELP_BLOCK_LAYER;
    public static final Item DRIPSTONE_BLOCK_LAYER;
    public static final Item EMERALD_BLOCK_LAYER;
    public static final Item EMERALD_ORE_LAYER;
    public static final Item END_STONE_BRICK_LAYER;
    public static final Item END_STONE_LAYER;
    public static final Item EXPOSED_COPPER_LAYER;
    public static final Item EXPOSED_CUT_COPPER_LAYER;
    public static final Item FIRE_CORAL_BLOCK_LAYER;
    public static final Item FLOWERING_AZALEA_LEAVES_LAYER;
    public static final Item GILDED_BLACKSTONE_LAYER;
    public static final Item GLASS_LAYER;
    public static final Item GLOWSTONE_LAYER;
    public static final Item GOLD_BLOCK_LAYER;
    public static final Item GOLD_ORE_LAYER;
    public static final Item GRANITE_LAYER;
    public static final Item GRASS_BLOCK_LAYER;
    public static final Item GRAVEL_LAYER;
    public static final Item GRAY_CONCRETE_LAYER;
    public static final Item GRAY_CONCRETE_POWDER_LAYER;
    public static final Item GRAY_GLAZED_TERRACOTTA_LAYER;
    public static final Item GRAY_STAINED_GLASS_LAYER;
    public static final Item GRAY_TERRACOTTA_LAYER;
    public static final Item GRAY_WOOL_LAYER;
    public static final Item GREEN_CONCRETE_LAYER;
    public static final Item GREEN_CONCRETE_POWDER_LAYER;
    public static final Item GREEN_GLAZED_TERRACOTTA_LAYER;
    public static final Item GREEN_STAINED_GLASS_LAYER;
    public static final Item GREEN_TERRACOTTA_LAYER;
    public static final Item GREEN_WOOL_LAYER;
    public static final Item HAY_BLOCK_LAYER;
    public static final Item HONEYCOMB_BLOCK_LAYER;
    public static final Item HONEY_BLOCK_LAYER;
    public static final Item HORN_CORAL_BLOCK_LAYER;
    public static final Item ICE_LAYER;
    public static final Item IRON_BLOCK_LAYER;
    public static final Item IRON_ORE_LAYER;
    public static final Item JUNGLE_LAYER;
    public static final Item JUNGLE_LEAVES_LAYER;
    public static final Item JUNGLE_LOG_LAYER;
    public static final Item JUNGLE_WOOD_LAYER;
    public static final Item LAPIS_BLOCK_LAYER;
    public static final Item LAPIS_ORE_LAYER;
    public static final Item LIGHT_BLUE_CONCRETE_LAYER;
    public static final Item LIGHT_BLUE_CONCRETE_POWDER_LAYER;
    public static final Item LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER;
    public static final Item LIGHT_BLUE_STAINED_GLASS_LAYER;
    public static final Item LIGHT_BLUE_TERRACOTTA_LAYER;
    public static final Item LIGHT_BLUE_WOOL_LAYER;
    public static final Item LIGHT_GRAY_CONCRETE_LAYER;
    public static final Item LIGHT_GRAY_CONCRETE_POWDER_LAYER;
    public static final Item LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER;
    public static final Item LIGHT_GRAY_STAINED_GLASS_LAYER;
    public static final Item LIGHT_GRAY_TERRACOTTA_LAYER;
    public static final Item LIGHT_GRAY_WOOL_LAYER;
    public static final Item LIME_CONCRETE_LAYER;
    public static final Item LIME_CONCRETE_POWDER_LAYER;
    public static final Item LIME_GLAZED_TERRACOTTA_LAYER;
    public static final Item LIME_STAINED_GLASS_LAYER;
    public static final Item LIME_TERRACOTTA_LAYER;
    public static final Item LIME_WOOL_LAYER;
    public static final Item MAGENTA_CONCRETE_LAYER;
    public static final Item MAGENTA_CONCRETE_POWDER_LAYER;
    public static final Item MAGENTA_GLAZED_TERRACOTTA_LAYER;
    public static final Item MAGENTA_STAINED_GLASS_LAYER;
    public static final Item MAGENTA_TERRACOTTA_LAYER;
    public static final Item MAGENTA_WOOL_LAYER;
    public static final Item MAGMA_BLOCK_LAYER;
    public static final Item MANGROVE_LAYER;
    public static final Item MANGROVE_LEAVES_LAYER;
    public static final Item MANGROVE_LOG_LAYER;
    public static final Item MANGROVE_ROOTS_LAYER;
    public static final Item MANGROVE_WOOD_LAYER;
    public static final Item MOSSY_COBBLESTONE_LAYER;
    public static final Item MOSSY_STONE_BRICK_LAYER;
    public static final Item MOSS_LAYER;
    public static final Item MUDDY_MANGROVE_ROOTS_LAYER;
    public static final Item MUD_BRICK_LAYER;
    public static final Item MUD_LAYER;
    public static final Item MYCELIUM_LAYER;
    public static final Item NETHERITE_BLOCK_LAYER;
    public static final Item NETHERRACK_LAYER;
    public static final Item NETHER_BRICK_BLOCK_LAYER;
    public static final Item NETHER_GOLD_ORE_LAYER;
    public static final Item NETHER_QUARTZ_ORE_LAYER;
    public static final Item NETHER_WART_BLOCK_LAYER;
    public static final Item OAK_LAYER;
    public static final Item OAK_LEAVES_LAYER;
    public static final Item OAK_LOG_LAYER;
    public static final Item OAK_WOOD_LAYER;
    public static final Item OBSIDIAN_LAYER;
    public static final Item OCHRE_FROGLIGHT_LAYER;
    public static final Item ORANGE_CONCRETE_LAYER;
    public static final Item ORANGE_CONCRETE_POWDER_LAYER;
    public static final Item ORANGE_GLAZED_TERRACOTTA_LAYER;
    public static final Item ORANGE_STAINED_GLASS_LAYER;
    public static final Item ORANGE_TERRACOTTA_LAYER;
    public static final Item ORANGE_WOOL_LAYER;
    public static final Item OXIDIZED_COPPER_LAYER;
    public static final Item OXIDIZED_CUT_COPPER_LAYER;
    public static final Item PACKED_ICE_LAYER;
    public static final Item PACKED_MUD_LAYER;
    public static final Item PEARLESCENT_FROGLIGHT_LAYER;
    public static final Item PINK_CONCRETE_LAYER;
    public static final Item PINK_CONCRETE_POWDER_LAYER;
    public static final Item PINK_GLAZED_TERRACOTTA_LAYER;
    public static final Item PINK_STAINED_GLASS_LAYER;
    public static final Item PINK_TERRACOTTA_LAYER;
    public static final Item PINK_WOOL_LAYER;
    public static final Item PODZOL_LAYER;
    public static final Item POLISHED_ANDESITE_LAYER;
    public static final Item POLISHED_BASALT_LAYER;
    public static final Item POLISHED_BLACKSTONE_BRICK_LAYER;
    public static final Item POLISHED_BLACKSTONE_LAYER;
    public static final Item POLISHED_DEEPSLATE_LAYER;
    public static final Item POLISHED_DIORITE_LAYER;
    public static final Item POLISHED_GRANITE_LAYER;
    public static final Item PRISMARINE_BRICK_LAYER;
    public static final Item PRISMARINE_LAYER;
    public static final Item PURPLE_CONCRETE_LAYER;
    public static final Item PURPLE_CONCRETE_POWDER_LAYER;
    public static final Item PURPLE_GLAZED_TERRACOTTA_LAYER;
    public static final Item PURPLE_STAINED_GLASS_LAYER;
    public static final Item PURPLE_TERRACOTTA_LAYER;
    public static final Item PURPLE_WOOL_LAYER;
    public static final Item PURPUR_BLOCK_LAYER;
    public static final Item PURPUR_PILLAR_LAYER;
    public static final Item QUARTZ_BLOCK_LAYER;
    public static final Item QUARTZ_BRICK_LAYER;
    public static final Item QUARTZ_PILLAR_LAYER;
    public static final Item RAW_COPPER_BLOCK_LAYER;
    public static final Item RAW_GOLD_BLOCK_LAYER;
    public static final Item RAW_IRON_BLOCK_LAYER;
    public static final Item REDSTONE_BLOCK_LAYER;
    public static final Item REDSTONE_ORE_LAYER;
    public static final Item RED_CONCRETE_LAYER;
    public static final Item RED_CONCRETE_POWDER_LAYER;
    public static final Item RED_GLAZED_TERRACOTTA_LAYER;
    public static final Item RED_NETHER_BRICK_LAYER;
    public static final Item RED_SANDSTONE_LAYER;
    public static final Item RED_SAND_LAYER;
    public static final Item RED_STAINED_GLASS_LAYER;
    public static final Item RED_TERRACOTTA_LAYER;
    public static final Item RED_WOOL_LAYER;
    public static final Item REINFORCED_DEEPSLATE_LAYER;
    public static final Item ROOTED_DIRT_LAYER;
    public static final Item SANDSTONE_LAYER;
    public static final Item SAND_LAYER;
    public static final Item SCULK_CATALYST_LAYER;
    public static final Item SCULK_LAYER;
    public static final Item SHROOMLIGHT_LAYER;
    public static final Item SLIME_BLOCK_LAYER;
    public static final Item SMOOTH_BASALT_LAYER;
    public static final Item SMOOTH_QUARTZ_BLOCK_LAYER;
    public static final Item SMOOTH_RED_SANDSTONE_LAYER;
    public static final Item SMOOTH_SANDSTONE_LAYER;
    public static final Item SMOOTH_STONE_LAYER;
    public static final Item SOUL_SAND_LAYER;
    public static final Item SOUL_SOIL_LAYER;
    public static final Item SPONGE_LAYER;
    public static final Item SPRUCE_LAYER;
    public static final Item SPRUCE_LEAVES_LAYER;
    public static final Item SPRUCE_LOG_LAYER;
    public static final Item SPRUCE_WOOD_LAYER;
    public static final Item STONE_BRICK_LAYER;
    public static final Item STONE_LAYER;
    public static final Item STRIPPED_ACACIA_LOG_LAYER;
    public static final Item STRIPPED_ACACIA_WOOD_LAYER;
    public static final Item STRIPPED_BAMBOO_BLOCK_LAYER;
    public static final Item STRIPPED_BIRCH_LOG_LAYER;
    public static final Item STRIPPED_BIRCH_WOOD_LAYER;
    public static final Item STRIPPED_CHERRY_LOG_LAYER;
    public static final Item STRIPPED_CHERRY_WOOD_LAYER;
    public static final Item STRIPPED_CRIMSON_HYPHAE_LAYER;
    public static final Item STRIPPED_CRIMSON_STEM_LAYER;
    public static final Item STRIPPED_DARK_OAK_LOG_LAYER;
    public static final Item STRIPPED_DARK_OAK_WOOD_LAYER;
    public static final Item STRIPPED_JUNGLE_LOG_LAYER;
    public static final Item STRIPPED_JUNGLE_WOOD_LAYER;
    public static final Item STRIPPED_MANGROVE_LOG_LAYER;
    public static final Item STRIPPED_MANGROVE_WOOD_LAYER;
    public static final Item STRIPPED_OAK_LOG_LAYER;
    public static final Item STRIPPED_OAK_WOOD_LAYER;
    public static final Item STRIPPED_SPRUCE_LOG_LAYER;
    public static final Item STRIPPED_SPRUCE_WOOD_LAYER;
    public static final Item STRIPPED_WARPED_HYPHAE_LAYER;
    public static final Item STRIPPED_WARPED_STEM_LAYER;
    public static final Item TARGET_LAYER;
    public static final Item TERRACOTTA_LAYER;
    public static final Item TINTED_GLASS_LAYER;
    public static final Item TUBE_CORAL_BLOCK_LAYER;
    public static final Item TUFF_LAYER;
    public static final Item VERDANT_FROGLIGHT_LAYER;
    public static final Item WARPED_HYPHAE_LAYER;
    public static final Item WARPED_LAYER;
    public static final Item WARPED_NYLIUM_LAYER;
    public static final Item WARPED_STEM_LAYER;
    public static final Item WARPED_WART_BLOCK_LAYER;
    public static final Item WAXED_COPPER_BLOCK_LAYER;
    public static final Item WAXED_CUT_COPPER_LAYER;
    public static final Item WAXED_EXPOSED_COPPER_LAYER;
    public static final Item WAXED_EXPOSED_CUT_COPPER_LAYER;
    public static final Item WAXED_WEATHERED_COPPER_LAYER;
    public static final Item WAXED_WEATHERED_CUT_COPPER_LAYER;
    public static final Item WEATHERED_COPPER_LAYER;
    public static final Item WEATHERED_CUT_COPPER_LAYER;
    public static final Item WET_SPONGE_LAYER;
    public static final Item WHITE_CONCRETE_LAYER;
    public static final Item WHITE_CONCRETE_POWDER_LAYER;
    public static final Item WHITE_GLAZED_TERRACOTTA_LAYER;
    public static final Item WHITE_STAINED_GLASS_LAYER;
    public static final Item WHITE_TERRACOTTA_LAYER;
    public static final Item WHITE_WOOL_LAYER;
    public static final Item YELLOW_CONCRETE_LAYER;
    public static final Item YELLOW_CONCRETE_POWDER_LAYER;
    public static final Item YELLOW_GLAZED_TERRACOTTA_LAYER;
    public static final Item YELLOW_STAINED_GLASS_LAYER;
    public static final Item YELLOW_TERRACOTTA_LAYER;
    public static final Item YELLOW_WOOL_LAYER;

    public static void register() {
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "acacia_layer"), ACACIA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "acacia_leaves_layer"), ACACIA_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "acacia_log_layer"), ACACIA_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "acacia_wood_layer"), ACACIA_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "amethyst_block_layer"), AMETHYST_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "ancient_debris_layer"), ANCIENT_DEBRIS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "andesite_layer"), ANDESITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "azalea_leaves_layer"), AZALEA_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bamboo_block_layer"), BAMBOO_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bamboo_layer"), BAMBOO_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bamboo_mosaic_layer"), BAMBOO_MOSAIC_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "basalt_layer"), BASALT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bedrock_layer"), BEDROCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "birch_layer"), BIRCH_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "birch_leaves_layer"), BIRCH_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "birch_log_layer"), BIRCH_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "birch_wood_layer"), BIRCH_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blackstone_layer"), BLACKSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_concrete_layer"), BLACK_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_concrete_powder_layer"), BLACK_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_glazed_terracotta_layer"), BLACK_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_stained_glass_layer"), BLACK_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_terracotta_layer"), BLACK_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "black_wool_layer"), BLACK_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_concrete_layer"), BLUE_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_concrete_powder_layer"), BLUE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_glazed_terracotta_layer"), BLUE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_ice_layer"), BLUE_ICE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_stained_glass_layer"), BLUE_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_terracotta_layer"), BLUE_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "blue_wool_layer"), BLUE_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bone_block_layer"), BONE_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brain_coral_block_layer"), BRAIN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brick_block_layer"), BRICK_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_concrete_layer"), BROWN_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_concrete_powder_layer"), BROWN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_glazed_terracotta_layer"), BROWN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_stained_glass_layer"), BROWN_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_terracotta_layer"), BROWN_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "brown_wool_layer"), BROWN_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "bubble_coral_block_layer"), BUBBLE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "budding_amethyst_layer"), BUDDING_AMETHYST_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "calcite_layer"), CALCITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cherry_layer"), CHERRY_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cherry_leaves_layer"), CHERRY_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cherry_log_layer"), CHERRY_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cherry_wood_layer"), CHERRY_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_deepslate_layer"), CHISELED_DEEPSLATE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_nether_brick_layer"), CHISELED_NETHER_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_polished_blackstone_layer"), CHISELED_POLISHED_BLACKSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_quartz_block_layer"), CHISELED_QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_red_sandstone_layer"), CHISELED_RED_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_sandstone_layer"), CHISELED_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "chiseled_stone_brick_layer"), CHISELED_STONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "clay_block_layer"), CLAY_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "coal_block_layer"), COAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "coal_ore_layer"), COAL_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "coarse_dirt_layer"), COARSE_DIRT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cobbled_deepslate_layer"), COBBLED_DEEPSLATE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cobblestone_layer"), COBBLESTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "copper_block_layer"), COPPER_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "copper_ore_layer"), COPPER_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cracked_deepslate_brick_layer"), CRACKED_DEEPSLATE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cracked_deepslate_tile_layer"), CRACKED_DEEPSLATE_TILE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cracked_nether_brick_layer"), CRACKED_NETHER_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cracked_polished_blackstone_brick_layer"), CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cracked_stone_brick_layer"), CRACKED_STONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "crimson_hyphae_layer"), CRIMSON_HYPHAE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "crimson_layer"), CRIMSON_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "crimson_nylium_layer"), CRIMSON_NYLIUM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "crimson_stem_layer"), CRIMSON_STEM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "crying_obsidian_layer"), CRYING_OBSIDIAN_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cut_copper_layer"), CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cut_red_sandstone_layer"), CUT_RED_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cut_sandstone_layer"), CUT_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_concrete_layer"), CYAN_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_concrete_powder_layer"), CYAN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_glazed_terracotta_layer"), CYAN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_stained_glass_layer"), CYAN_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_terracotta_layer"), CYAN_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "cyan_wool_layer"), CYAN_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dark_oak_layer"), DARK_OAK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dark_oak_leaves_layer"), DARK_OAK_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dark_oak_log_layer"), DARK_OAK_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dark_oak_wood_layer"), DARK_OAK_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dark_prismarine_layer"), DARK_PRISMARINE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dead_brain_coral_block_layer"), DEAD_BRAIN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dead_bubble_coral_block_layer"), DEAD_BUBBLE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dead_fire_coral_block_layer"), DEAD_FIRE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dead_horn_coral_block_layer"), DEAD_HORN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dead_tube_coral_block_layer"), DEAD_TUBE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_brick_layer"), DEEPSLATE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_coal_ore_layer"), DEEPSLATE_COAL_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_copper_ore_layer"), DEEPSLATE_COPPER_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_diamond_ore_layer"), DEEPSLATE_DIAMOND_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_emerald_ore_layer"), DEEPSLATE_EMERALD_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_gold_ore_layer"), DEEPSLATE_GOLD_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_iron_ore_layer"), DEEPSLATE_IRON_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_lapis_ore_layer"), DEEPSLATE_LAPIS_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_layer"), DEEPSLATE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_redstone_ore_layer"), DEEPSLATE_REDSTONE_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "deepslate_tile_layer"), DEEPSLATE_TILE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "diamond_block_layer"), DIAMOND_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "diamond_ore_layer"), DIAMOND_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "diorite_layer"), DIORITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dirt_layer"), DIRT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dirt_path_layer"), DIRT_PATH_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dried_kelp_block_layer"), DRIED_KELP_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "dripstone_block_layer"), DRIPSTONE_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "emerald_block_layer"), EMERALD_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "emerald_ore_layer"), EMERALD_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "end_stone_brick_layer"), END_STONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "end_stone_layer"), END_STONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "exposed_copper_layer"), EXPOSED_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "exposed_cut_copper_layer"), EXPOSED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "fire_coral_block_layer"), FIRE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "flowering_azalea_leaves_layer"), FLOWERING_AZALEA_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gilded_blackstone_layer"), GILDED_BLACKSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "glass_layer"), GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "glowstone_layer"), GLOWSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gold_block_layer"), GOLD_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gold_ore_layer"), GOLD_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "granite_layer"), GRANITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "grass_block_layer"), GRASS_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gravel_layer"), GRAVEL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_concrete_layer"), GRAY_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_concrete_powder_layer"), GRAY_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_glazed_terracotta_layer"), GRAY_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_stained_glass_layer"), GRAY_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_terracotta_layer"), GRAY_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "gray_wool_layer"), GRAY_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_concrete_layer"), GREEN_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_concrete_powder_layer"), GREEN_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_glazed_terracotta_layer"), GREEN_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_stained_glass_layer"), GREEN_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_terracotta_layer"), GREEN_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "green_wool_layer"), GREEN_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "hay_block_layer"), HAY_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "honeycomb_block_layer"), HONEYCOMB_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "honey_block_layer"), HONEY_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "horn_coral_block_layer"), HORN_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "ice_layer"), ICE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "iron_block_layer"), IRON_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "iron_ore_layer"), IRON_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "jungle_layer"), JUNGLE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "jungle_leaves_layer"), JUNGLE_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "jungle_log_layer"), JUNGLE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "jungle_wood_layer"), JUNGLE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lapis_block_layer"), LAPIS_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lapis_ore_layer"), LAPIS_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_concrete_layer"), LIGHT_BLUE_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_concrete_powder_layer"), LIGHT_BLUE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_glazed_terracotta_layer"), LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_stained_glass_layer"), LIGHT_BLUE_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_terracotta_layer"), LIGHT_BLUE_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_blue_wool_layer"), LIGHT_BLUE_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_concrete_layer"), LIGHT_GRAY_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_concrete_powder_layer"), LIGHT_GRAY_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_glazed_terracotta_layer"), LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_stained_glass_layer"), LIGHT_GRAY_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_terracotta_layer"), LIGHT_GRAY_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "light_gray_wool_layer"), LIGHT_GRAY_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_concrete_layer"), LIME_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_concrete_powder_layer"), LIME_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_glazed_terracotta_layer"), LIME_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_stained_glass_layer"), LIME_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_terracotta_layer"), LIME_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "lime_wool_layer"), LIME_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_concrete_layer"), MAGENTA_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_concrete_powder_layer"), MAGENTA_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_glazed_terracotta_layer"), MAGENTA_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_stained_glass_layer"), MAGENTA_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_terracotta_layer"), MAGENTA_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magenta_wool_layer"), MAGENTA_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "magma_block_layer"), MAGMA_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mangrove_layer"), MANGROVE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mangrove_leaves_layer"), MANGROVE_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mangrove_log_layer"), MANGROVE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mangrove_roots_layer"), MANGROVE_ROOTS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mangrove_wood_layer"), MANGROVE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mossy_cobblestone_layer"), MOSSY_COBBLESTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mossy_stone_brick_layer"), MOSSY_STONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "moss_layer"), MOSS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "muddy_mangrove_roots_layer"), MUDDY_MANGROVE_ROOTS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mud_brick_layer"), MUD_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mud_layer"), MUD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "mycelium_layer"), MYCELIUM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "netherite_block_layer"), NETHERITE_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "netherrack_layer"), NETHERRACK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "nether_brick_block_layer"), NETHER_BRICK_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "nether_gold_ore_layer"), NETHER_GOLD_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "nether_quartz_ore_layer"), NETHER_QUARTZ_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "nether_wart_block_layer"), NETHER_WART_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oak_layer"), OAK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oak_leaves_layer"), OAK_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oak_log_layer"), OAK_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oak_wood_layer"), OAK_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "obsidian_layer"), OBSIDIAN_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "ochre_froglight_layer"), OCHRE_FROGLIGHT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_concrete_layer"), ORANGE_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_concrete_powder_layer"), ORANGE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_glazed_terracotta_layer"), ORANGE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_stained_glass_layer"), ORANGE_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_terracotta_layer"), ORANGE_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "orange_wool_layer"), ORANGE_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oxidized_copper_layer"), OXIDIZED_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "oxidized_cut_copper_layer"), OXIDIZED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "packed_ice_layer"), PACKED_ICE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "packed_mud_layer"), PACKED_MUD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pearlescent_froglight_layer"), PEARLESCENT_FROGLIGHT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_concrete_layer"), PINK_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_concrete_powder_layer"), PINK_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_glazed_terracotta_layer"), PINK_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_stained_glass_layer"), PINK_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_terracotta_layer"), PINK_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "pink_wool_layer"), PINK_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "podzol_layer"), PODZOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_andesite_layer"), POLISHED_ANDESITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_basalt_layer"), POLISHED_BASALT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_blackstone_brick_layer"), POLISHED_BLACKSTONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_blackstone_layer"), POLISHED_BLACKSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_deepslate_layer"), POLISHED_DEEPSLATE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_diorite_layer"), POLISHED_DIORITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "polished_granite_layer"), POLISHED_GRANITE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "prismarine_brick_layer"), PRISMARINE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "prismarine_layer"), PRISMARINE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_concrete_layer"), PURPLE_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_concrete_powder_layer"), PURPLE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_glazed_terracotta_layer"), PURPLE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_stained_glass_layer"), PURPLE_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_terracotta_layer"), PURPLE_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purple_wool_layer"), PURPLE_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purpur_block_layer"), PURPUR_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "purpur_pillar_layer"), PURPUR_PILLAR_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "quartz_block_layer"), QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "quartz_brick_layer"), QUARTZ_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "quartz_pillar_layer"), QUARTZ_PILLAR_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "raw_copper_block_layer"), RAW_COPPER_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "raw_gold_block_layer"), RAW_GOLD_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "raw_iron_block_layer"), RAW_IRON_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "redstone_block_layer"), REDSTONE_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "redstone_ore_layer"), REDSTONE_ORE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_concrete_layer"), RED_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_concrete_powder_layer"), RED_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_glazed_terracotta_layer"), RED_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_nether_brick_layer"), RED_NETHER_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_sandstone_layer"), RED_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_sand_layer"), RED_SAND_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_stained_glass_layer"), RED_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_terracotta_layer"), RED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "red_wool_layer"), RED_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "reinforced_deepslate_layer"), REINFORCED_DEEPSLATE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "rooted_dirt_layer"), ROOTED_DIRT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "sandstone_layer"), SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "sand_layer"), SAND_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "sculk_catalyst_layer"), SCULK_CATALYST_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "sculk_layer"), SCULK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "shroomlight_layer"), SHROOMLIGHT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "slime_block_layer"), SLIME_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "smooth_basalt_layer"), SMOOTH_BASALT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "smooth_quartz_block_layer"), SMOOTH_QUARTZ_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "smooth_red_sandstone_layer"), SMOOTH_RED_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "smooth_sandstone_layer"), SMOOTH_SANDSTONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "smooth_stone_layer"), SMOOTH_STONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "soul_sand_layer"), SOUL_SAND_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "soul_soil_layer"), SOUL_SOIL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "sponge_layer"), SPONGE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "spruce_layer"), SPRUCE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "spruce_leaves_layer"), SPRUCE_LEAVES_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "spruce_log_layer"), SPRUCE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "spruce_wood_layer"), SPRUCE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stone_brick_layer"), STONE_BRICK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stone_layer"), STONE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_acacia_log_layer"), STRIPPED_ACACIA_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_acacia_wood_layer"), STRIPPED_ACACIA_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_bamboo_block_layer"), STRIPPED_BAMBOO_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_birch_log_layer"), STRIPPED_BIRCH_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_birch_wood_layer"), STRIPPED_BIRCH_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_cherry_log_layer"), STRIPPED_CHERRY_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_cherry_wood_layer"), STRIPPED_CHERRY_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_crimson_hyphae_layer"), STRIPPED_CRIMSON_HYPHAE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_crimson_stem_layer"), STRIPPED_CRIMSON_STEM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_dark_oak_log_layer"), STRIPPED_DARK_OAK_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_dark_oak_wood_layer"), STRIPPED_DARK_OAK_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_jungle_log_layer"), STRIPPED_JUNGLE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_jungle_wood_layer"), STRIPPED_JUNGLE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_mangrove_log_layer"), STRIPPED_MANGROVE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_mangrove_wood_layer"), STRIPPED_MANGROVE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_oak_log_layer"), STRIPPED_OAK_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_oak_wood_layer"), STRIPPED_OAK_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_spruce_log_layer"), STRIPPED_SPRUCE_LOG_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_spruce_wood_layer"), STRIPPED_SPRUCE_WOOD_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_warped_hyphae_layer"), STRIPPED_WARPED_HYPHAE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "stripped_warped_stem_layer"), STRIPPED_WARPED_STEM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "target_layer"), TARGET_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "terracotta_layer"), TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "tinted_glass_layer"), TINTED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "tube_coral_block_layer"), TUBE_CORAL_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "tuff_layer"), TUFF_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "verdant_froglight_layer"), VERDANT_FROGLIGHT_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "warped_hyphae_layer"), WARPED_HYPHAE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "warped_layer"), WARPED_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "warped_nylium_layer"), WARPED_NYLIUM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "warped_stem_layer"), WARPED_STEM_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "warped_wart_block_layer"), WARPED_WART_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_copper_block_layer"), WAXED_COPPER_BLOCK_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_cut_copper_layer"), WAXED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_exposed_copper_layer"), WAXED_EXPOSED_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_exposed_cut_copper_layer"), WAXED_EXPOSED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_weathered_copper_layer"), WAXED_WEATHERED_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "waxed_weathered_cut_copper_layer"), WAXED_WEATHERED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "weathered_copper_layer"), WEATHERED_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "weathered_cut_copper_layer"), WEATHERED_CUT_COPPER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "wet_sponge_layer"), WET_SPONGE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_concrete_layer"), WHITE_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_concrete_powder_layer"), WHITE_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_glazed_terracotta_layer"), WHITE_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_stained_glass_layer"), WHITE_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_terracotta_layer"), WHITE_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "white_wool_layer"), WHITE_WOOL_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_concrete_layer"), YELLOW_CONCRETE_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_concrete_powder_layer"), YELLOW_CONCRETE_POWDER_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_glazed_terracotta_layer"), YELLOW_GLAZED_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_stained_glass_layer"), YELLOW_STAINED_GLASS_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_terracotta_layer"), YELLOW_TERRACOTTA_LAYER);
        Registry.register(Registries.ITEM, Identifier.of(MoreBlock.MOD_ID, "yellow_wool_layer"), YELLOW_WOOL_LAYER);

    }

    static {
        ACACIA_LAYER = new BlockItem(MoreBlockBlocks.ACACIA_LAYER, new Item.Settings());
        ACACIA_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.ACACIA_LEAVES_LAYER, new Item.Settings());
        ACACIA_LOG_LAYER = new BlockItem(MoreBlockBlocks.ACACIA_LOG_LAYER, new Item.Settings());
        ACACIA_WOOD_LAYER = new BlockItem(MoreBlockBlocks.ACACIA_WOOD_LAYER, new Item.Settings());
        AMETHYST_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.AMETHYST_BLOCK_LAYER, new Item.Settings());
        ANCIENT_DEBRIS_LAYER = new BlockItem(MoreBlockBlocks.ANCIENT_DEBRIS_LAYER, new Item.Settings());
        ANDESITE_LAYER = new BlockItem(MoreBlockBlocks.ANDESITE_LAYER, new Item.Settings());
        AZALEA_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.AZALEA_LEAVES_LAYER, new Item.Settings());
        BAMBOO_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.BAMBOO_BLOCK_LAYER, new Item.Settings());
        BAMBOO_LAYER = new BlockItem(MoreBlockBlocks.BAMBOO_LAYER, new Item.Settings());
        BAMBOO_MOSAIC_LAYER = new BlockItem(MoreBlockBlocks.BAMBOO_MOSAIC_LAYER, new Item.Settings());
        BASALT_LAYER = new BlockItem(MoreBlockBlocks.BASALT_LAYER, new Item.Settings());
        BEDROCK_LAYER = new BlockItem(MoreBlockBlocks.BEDROCK_LAYER, new Item.Settings());
        BIRCH_LAYER = new BlockItem(MoreBlockBlocks.BIRCH_LAYER, new Item.Settings());
        BIRCH_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.BIRCH_LEAVES_LAYER, new Item.Settings());
        BIRCH_LOG_LAYER = new BlockItem(MoreBlockBlocks.BIRCH_LOG_LAYER, new Item.Settings());
        BIRCH_WOOD_LAYER = new BlockItem(MoreBlockBlocks.BIRCH_WOOD_LAYER, new Item.Settings());
        BLACKSTONE_LAYER = new BlockItem(MoreBlockBlocks.BLACKSTONE_LAYER, new Item.Settings());
        BLACK_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.BLACK_CONCRETE_LAYER, new Item.Settings());
        BLACK_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.BLACK_CONCRETE_POWDER_LAYER, new Item.Settings());
        BLACK_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BLACK_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        BLACK_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.BLACK_STAINED_GLASS_LAYER, new Item.Settings());
        BLACK_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BLACK_TERRACOTTA_LAYER, new Item.Settings());
        BLACK_WOOL_LAYER = new BlockItem(MoreBlockBlocks.BLACK_WOOL_LAYER, new Item.Settings());
        BLUE_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.BLUE_CONCRETE_LAYER, new Item.Settings());
        BLUE_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.BLUE_CONCRETE_POWDER_LAYER, new Item.Settings());
        BLUE_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BLUE_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        BLUE_ICE_LAYER = new BlockItem(MoreBlockBlocks.BLUE_ICE_LAYER, new Item.Settings());
        BLUE_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.BLUE_STAINED_GLASS_LAYER, new Item.Settings());
        BLUE_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BLUE_TERRACOTTA_LAYER, new Item.Settings());
        BLUE_WOOL_LAYER = new BlockItem(MoreBlockBlocks.BLUE_WOOL_LAYER, new Item.Settings());
        BONE_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.BONE_BLOCK_LAYER, new Item.Settings());
        BRAIN_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.BRAIN_CORAL_BLOCK_LAYER, new Item.Settings());
        BRICK_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.BRICK_BLOCK_LAYER, new Item.Settings());
        BROWN_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.BROWN_CONCRETE_LAYER, new Item.Settings());
        BROWN_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.BROWN_CONCRETE_POWDER_LAYER, new Item.Settings());
        BROWN_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BROWN_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        BROWN_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.BROWN_STAINED_GLASS_LAYER, new Item.Settings());
        BROWN_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.BROWN_TERRACOTTA_LAYER, new Item.Settings());
        BROWN_WOOL_LAYER = new BlockItem(MoreBlockBlocks.BROWN_WOOL_LAYER, new Item.Settings());
        BUBBLE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.BUBBLE_CORAL_BLOCK_LAYER, new Item.Settings());
        BUDDING_AMETHYST_LAYER = new BlockItem(MoreBlockBlocks.BUDDING_AMETHYST_LAYER, new Item.Settings());
        CALCITE_LAYER = new BlockItem(MoreBlockBlocks.CALCITE_LAYER, new Item.Settings());
        CHERRY_LAYER = new BlockItem(MoreBlockBlocks.CHERRY_LAYER, new Item.Settings());
        CHERRY_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.CHERRY_LEAVES_LAYER, new Item.Settings());
        CHERRY_LOG_LAYER = new BlockItem(MoreBlockBlocks.CHERRY_LOG_LAYER, new Item.Settings());
        CHERRY_WOOD_LAYER = new BlockItem(MoreBlockBlocks.CHERRY_WOOD_LAYER, new Item.Settings());
        CHISELED_DEEPSLATE_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_DEEPSLATE_LAYER, new Item.Settings());
        CHISELED_NETHER_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_NETHER_BRICK_LAYER, new Item.Settings());
        CHISELED_POLISHED_BLACKSTONE_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_POLISHED_BLACKSTONE_LAYER, new Item.Settings());
        CHISELED_QUARTZ_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_QUARTZ_BLOCK_LAYER, new Item.Settings());
        CHISELED_RED_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_RED_SANDSTONE_LAYER, new Item.Settings());
        CHISELED_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_SANDSTONE_LAYER, new Item.Settings());
        CHISELED_STONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CHISELED_STONE_BRICK_LAYER, new Item.Settings());
        CLAY_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.CLAY_BLOCK_LAYER, new Item.Settings());
        COAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.COAL_BLOCK_LAYER, new Item.Settings());
        COAL_ORE_LAYER = new BlockItem(MoreBlockBlocks.COAL_ORE_LAYER, new Item.Settings());
        COARSE_DIRT_LAYER = new BlockItem(MoreBlockBlocks.COARSE_DIRT_LAYER, new Item.Settings());
        COBBLED_DEEPSLATE_LAYER = new BlockItem(MoreBlockBlocks.COBBLED_DEEPSLATE_LAYER, new Item.Settings());
        COBBLESTONE_LAYER = new BlockItem(MoreBlockBlocks.COBBLESTONE_LAYER, new Item.Settings());
        COPPER_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.COPPER_BLOCK_LAYER, new Item.Settings());
        COPPER_ORE_LAYER = new BlockItem(MoreBlockBlocks.COPPER_ORE_LAYER, new Item.Settings());
        CRACKED_DEEPSLATE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CRACKED_DEEPSLATE_BRICK_LAYER, new Item.Settings());
        CRACKED_DEEPSLATE_TILE_LAYER = new BlockItem(MoreBlockBlocks.CRACKED_DEEPSLATE_TILE_LAYER, new Item.Settings());
        CRACKED_NETHER_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CRACKED_NETHER_BRICK_LAYER, new Item.Settings());
        CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_LAYER, new Item.Settings());
        CRACKED_STONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.CRACKED_STONE_BRICK_LAYER, new Item.Settings());
        CRIMSON_HYPHAE_LAYER = new BlockItem(MoreBlockBlocks.CRIMSON_HYPHAE_LAYER, new Item.Settings());
        CRIMSON_LAYER = new BlockItem(MoreBlockBlocks.CRIMSON_LAYER, new Item.Settings());
        CRIMSON_NYLIUM_LAYER = new BlockItem(MoreBlockBlocks.CRIMSON_NYLIUM_LAYER, new Item.Settings());
        CRIMSON_STEM_LAYER = new BlockItem(MoreBlockBlocks.CRIMSON_STEM_LAYER, new Item.Settings());
        CRYING_OBSIDIAN_LAYER = new BlockItem(MoreBlockBlocks.CRYING_OBSIDIAN_LAYER, new Item.Settings());
        CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.CUT_COPPER_LAYER, new Item.Settings());
        CUT_RED_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.CUT_RED_SANDSTONE_LAYER, new Item.Settings());
        CUT_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.CUT_SANDSTONE_LAYER, new Item.Settings());
        CYAN_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.CYAN_CONCRETE_LAYER, new Item.Settings());
        CYAN_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.CYAN_CONCRETE_POWDER_LAYER, new Item.Settings());
        CYAN_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.CYAN_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        CYAN_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.CYAN_STAINED_GLASS_LAYER, new Item.Settings());
        CYAN_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.CYAN_TERRACOTTA_LAYER, new Item.Settings());
        CYAN_WOOL_LAYER = new BlockItem(MoreBlockBlocks.CYAN_WOOL_LAYER, new Item.Settings());
        DARK_OAK_LAYER = new BlockItem(MoreBlockBlocks.DARK_OAK_LAYER, new Item.Settings());
        DARK_OAK_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.DARK_OAK_LEAVES_LAYER, new Item.Settings());
        DARK_OAK_LOG_LAYER = new BlockItem(MoreBlockBlocks.DARK_OAK_LOG_LAYER, new Item.Settings());
        DARK_OAK_WOOD_LAYER = new BlockItem(MoreBlockBlocks.DARK_OAK_WOOD_LAYER, new Item.Settings());
        DARK_PRISMARINE_LAYER = new BlockItem(MoreBlockBlocks.DARK_PRISMARINE_LAYER, new Item.Settings());
        DEAD_BRAIN_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DEAD_BRAIN_CORAL_BLOCK_LAYER, new Item.Settings());
        DEAD_BUBBLE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DEAD_BUBBLE_CORAL_BLOCK_LAYER, new Item.Settings());
        DEAD_FIRE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DEAD_FIRE_CORAL_BLOCK_LAYER, new Item.Settings());
        DEAD_HORN_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DEAD_HORN_CORAL_BLOCK_LAYER, new Item.Settings());
        DEAD_TUBE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DEAD_TUBE_CORAL_BLOCK_LAYER, new Item.Settings());
        DEEPSLATE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_BRICK_LAYER, new Item.Settings());
        DEEPSLATE_COAL_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_COAL_ORE_LAYER, new Item.Settings());
        DEEPSLATE_COPPER_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_COPPER_ORE_LAYER, new Item.Settings());
        DEEPSLATE_DIAMOND_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_DIAMOND_ORE_LAYER, new Item.Settings());
        DEEPSLATE_EMERALD_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_EMERALD_ORE_LAYER, new Item.Settings());
        DEEPSLATE_GOLD_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_GOLD_ORE_LAYER, new Item.Settings());
        DEEPSLATE_IRON_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_IRON_ORE_LAYER, new Item.Settings());
        DEEPSLATE_LAPIS_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_LAPIS_ORE_LAYER, new Item.Settings());
        DEEPSLATE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_LAYER, new Item.Settings());
        DEEPSLATE_REDSTONE_ORE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_REDSTONE_ORE_LAYER, new Item.Settings());
        DEEPSLATE_TILE_LAYER = new BlockItem(MoreBlockBlocks.DEEPSLATE_TILE_LAYER, new Item.Settings());
        DIAMOND_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DIAMOND_BLOCK_LAYER, new Item.Settings());
        DIAMOND_ORE_LAYER = new BlockItem(MoreBlockBlocks.DIAMOND_ORE_LAYER, new Item.Settings());
        DIORITE_LAYER = new BlockItem(MoreBlockBlocks.DIORITE_LAYER, new Item.Settings());
        DIRT_LAYER = new BlockItem(MoreBlockBlocks.DIRT_LAYER, new Item.Settings());
        DIRT_PATH_LAYER = new BlockItem(MoreBlockBlocks.DIRT_PATH_LAYER, new Item.Settings());
        DRIED_KELP_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DRIED_KELP_BLOCK_LAYER, new Item.Settings());
        DRIPSTONE_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.DRIPSTONE_BLOCK_LAYER, new Item.Settings());
        EMERALD_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.EMERALD_BLOCK_LAYER, new Item.Settings());
        EMERALD_ORE_LAYER = new BlockItem(MoreBlockBlocks.EMERALD_ORE_LAYER, new Item.Settings());
        END_STONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.END_STONE_BRICK_LAYER, new Item.Settings());
        END_STONE_LAYER = new BlockItem(MoreBlockBlocks.END_STONE_LAYER, new Item.Settings());
        EXPOSED_COPPER_LAYER = new BlockItem(MoreBlockBlocks.EXPOSED_COPPER_LAYER, new Item.Settings());
        EXPOSED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.EXPOSED_CUT_COPPER_LAYER, new Item.Settings());
        FIRE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.FIRE_CORAL_BLOCK_LAYER, new Item.Settings());
        FLOWERING_AZALEA_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.FLOWERING_AZALEA_LEAVES_LAYER, new Item.Settings());
        GILDED_BLACKSTONE_LAYER = new BlockItem(MoreBlockBlocks.GILDED_BLACKSTONE_LAYER, new Item.Settings());
        GLASS_LAYER = new BlockItem(MoreBlockBlocks.GLASS_LAYER, new Item.Settings());
        GLOWSTONE_LAYER = new BlockItem(MoreBlockBlocks.GLOWSTONE_LAYER, new Item.Settings());
        GOLD_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.GOLD_BLOCK_LAYER, new Item.Settings());
        GOLD_ORE_LAYER = new BlockItem(MoreBlockBlocks.GOLD_ORE_LAYER, new Item.Settings());
        GRANITE_LAYER = new BlockItem(MoreBlockBlocks.GRANITE_LAYER, new Item.Settings());
        GRASS_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.GRASS_BLOCK_LAYER, new Item.Settings());
        GRAVEL_LAYER = new BlockItem(MoreBlockBlocks.GRAVEL_LAYER, new Item.Settings());
        GRAY_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.GRAY_CONCRETE_LAYER, new Item.Settings());
        GRAY_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.GRAY_CONCRETE_POWDER_LAYER, new Item.Settings());
        GRAY_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.GRAY_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        GRAY_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.GRAY_STAINED_GLASS_LAYER, new Item.Settings());
        GRAY_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.GRAY_TERRACOTTA_LAYER, new Item.Settings());
        GRAY_WOOL_LAYER = new BlockItem(MoreBlockBlocks.GRAY_WOOL_LAYER, new Item.Settings());
        GREEN_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.GREEN_CONCRETE_LAYER, new Item.Settings());
        GREEN_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.GREEN_CONCRETE_POWDER_LAYER, new Item.Settings());
        GREEN_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.GREEN_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        GREEN_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.GREEN_STAINED_GLASS_LAYER, new Item.Settings());
        GREEN_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.GREEN_TERRACOTTA_LAYER, new Item.Settings());
        GREEN_WOOL_LAYER = new BlockItem(MoreBlockBlocks.GREEN_WOOL_LAYER, new Item.Settings());
        HAY_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.HAY_BLOCK_LAYER, new Item.Settings());
        HONEYCOMB_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.HONEYCOMB_BLOCK_LAYER, new Item.Settings());
        HONEY_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.HONEY_BLOCK_LAYER, new Item.Settings());
        HORN_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.HORN_CORAL_BLOCK_LAYER, new Item.Settings());
        ICE_LAYER = new BlockItem(MoreBlockBlocks.ICE_LAYER, new Item.Settings());
        IRON_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.IRON_BLOCK_LAYER, new Item.Settings());
        IRON_ORE_LAYER = new BlockItem(MoreBlockBlocks.IRON_ORE_LAYER, new Item.Settings());
        JUNGLE_LAYER = new BlockItem(MoreBlockBlocks.JUNGLE_LAYER, new Item.Settings());
        JUNGLE_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.JUNGLE_LEAVES_LAYER, new Item.Settings());
        JUNGLE_LOG_LAYER = new BlockItem(MoreBlockBlocks.JUNGLE_LOG_LAYER, new Item.Settings());
        JUNGLE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.JUNGLE_WOOD_LAYER, new Item.Settings());
        LAPIS_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.LAPIS_BLOCK_LAYER, new Item.Settings());
        LAPIS_ORE_LAYER = new BlockItem(MoreBlockBlocks.LAPIS_ORE_LAYER, new Item.Settings());
        LIGHT_BLUE_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_CONCRETE_LAYER, new Item.Settings());
        LIGHT_BLUE_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_CONCRETE_POWDER_LAYER, new Item.Settings());
        LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        LIGHT_BLUE_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_STAINED_GLASS_LAYER, new Item.Settings());
        LIGHT_BLUE_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_TERRACOTTA_LAYER, new Item.Settings());
        LIGHT_BLUE_WOOL_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_BLUE_WOOL_LAYER, new Item.Settings());
        LIGHT_GRAY_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_CONCRETE_LAYER, new Item.Settings());
        LIGHT_GRAY_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_CONCRETE_POWDER_LAYER, new Item.Settings());
        LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        LIGHT_GRAY_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_STAINED_GLASS_LAYER, new Item.Settings());
        LIGHT_GRAY_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_TERRACOTTA_LAYER, new Item.Settings());
        LIGHT_GRAY_WOOL_LAYER = new BlockItem(MoreBlockBlocks.LIGHT_GRAY_WOOL_LAYER, new Item.Settings());
        LIME_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.LIME_CONCRETE_LAYER, new Item.Settings());
        LIME_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.LIME_CONCRETE_POWDER_LAYER, new Item.Settings());
        LIME_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIME_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        LIME_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.LIME_STAINED_GLASS_LAYER, new Item.Settings());
        LIME_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.LIME_TERRACOTTA_LAYER, new Item.Settings());
        LIME_WOOL_LAYER = new BlockItem(MoreBlockBlocks.LIME_WOOL_LAYER, new Item.Settings());
        MAGENTA_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_CONCRETE_LAYER, new Item.Settings());
        MAGENTA_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_CONCRETE_POWDER_LAYER, new Item.Settings());
        MAGENTA_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        MAGENTA_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_STAINED_GLASS_LAYER, new Item.Settings());
        MAGENTA_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_TERRACOTTA_LAYER, new Item.Settings());
        MAGENTA_WOOL_LAYER = new BlockItem(MoreBlockBlocks.MAGENTA_WOOL_LAYER, new Item.Settings());
        MAGMA_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.MAGMA_BLOCK_LAYER, new Item.Settings());
        MANGROVE_LAYER = new BlockItem(MoreBlockBlocks.MANGROVE_LAYER, new Item.Settings());
        MANGROVE_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.MANGROVE_LEAVES_LAYER, new Item.Settings());
        MANGROVE_LOG_LAYER = new BlockItem(MoreBlockBlocks.MANGROVE_LOG_LAYER, new Item.Settings());
        MANGROVE_ROOTS_LAYER = new BlockItem(MoreBlockBlocks.MANGROVE_ROOTS_LAYER, new Item.Settings());
        MANGROVE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.MANGROVE_WOOD_LAYER, new Item.Settings());
        MOSSY_COBBLESTONE_LAYER = new BlockItem(MoreBlockBlocks.MOSSY_COBBLESTONE_LAYER, new Item.Settings());
        MOSSY_STONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.MOSSY_STONE_BRICK_LAYER, new Item.Settings());
        MOSS_LAYER = new BlockItem(MoreBlockBlocks.MOSS_LAYER, new Item.Settings());
        MUDDY_MANGROVE_ROOTS_LAYER = new BlockItem(MoreBlockBlocks.MUDDY_MANGROVE_ROOTS_LAYER, new Item.Settings());
        MUD_BRICK_LAYER = new BlockItem(MoreBlockBlocks.MUD_BRICK_LAYER, new Item.Settings());
        MUD_LAYER = new BlockItem(MoreBlockBlocks.MUD_LAYER, new Item.Settings());
        MYCELIUM_LAYER = new BlockItem(MoreBlockBlocks.MYCELIUM_LAYER, new Item.Settings());
        NETHERITE_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.NETHERITE_BLOCK_LAYER, new Item.Settings());
        NETHERRACK_LAYER = new BlockItem(MoreBlockBlocks.NETHERRACK_LAYER, new Item.Settings());
        NETHER_BRICK_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.NETHER_BRICK_BLOCK_LAYER, new Item.Settings());
        NETHER_GOLD_ORE_LAYER = new BlockItem(MoreBlockBlocks.NETHER_GOLD_ORE_LAYER, new Item.Settings());
        NETHER_QUARTZ_ORE_LAYER = new BlockItem(MoreBlockBlocks.NETHER_QUARTZ_ORE_LAYER, new Item.Settings());
        NETHER_WART_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.NETHER_WART_BLOCK_LAYER, new Item.Settings());
        OAK_LAYER = new BlockItem(MoreBlockBlocks.OAK_LAYER, new Item.Settings());
        OAK_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.OAK_LEAVES_LAYER, new Item.Settings());
        OAK_LOG_LAYER = new BlockItem(MoreBlockBlocks.OAK_LOG_LAYER, new Item.Settings());
        OAK_WOOD_LAYER = new BlockItem(MoreBlockBlocks.OAK_WOOD_LAYER, new Item.Settings());
        OBSIDIAN_LAYER = new BlockItem(MoreBlockBlocks.OBSIDIAN_LAYER, new Item.Settings());
        OCHRE_FROGLIGHT_LAYER = new BlockItem(MoreBlockBlocks.OCHRE_FROGLIGHT_LAYER, new Item.Settings());
        ORANGE_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_CONCRETE_LAYER, new Item.Settings());
        ORANGE_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_CONCRETE_POWDER_LAYER, new Item.Settings());
        ORANGE_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        ORANGE_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_STAINED_GLASS_LAYER, new Item.Settings());
        ORANGE_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_TERRACOTTA_LAYER, new Item.Settings());
        ORANGE_WOOL_LAYER = new BlockItem(MoreBlockBlocks.ORANGE_WOOL_LAYER, new Item.Settings());
        OXIDIZED_COPPER_LAYER = new BlockItem(MoreBlockBlocks.OXIDIZED_COPPER_LAYER, new Item.Settings());
        OXIDIZED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.OXIDIZED_CUT_COPPER_LAYER, new Item.Settings());
        PACKED_ICE_LAYER = new BlockItem(MoreBlockBlocks.PACKED_ICE_LAYER, new Item.Settings());
        PACKED_MUD_LAYER = new BlockItem(MoreBlockBlocks.PACKED_MUD_LAYER, new Item.Settings());
        PEARLESCENT_FROGLIGHT_LAYER = new BlockItem(MoreBlockBlocks.PEARLESCENT_FROGLIGHT_LAYER, new Item.Settings());
        PINK_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.PINK_CONCRETE_LAYER, new Item.Settings());
        PINK_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.PINK_CONCRETE_POWDER_LAYER, new Item.Settings());
        PINK_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.PINK_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        PINK_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.PINK_STAINED_GLASS_LAYER, new Item.Settings());
        PINK_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.PINK_TERRACOTTA_LAYER, new Item.Settings());
        PINK_WOOL_LAYER = new BlockItem(MoreBlockBlocks.PINK_WOOL_LAYER, new Item.Settings());
        PODZOL_LAYER = new BlockItem(MoreBlockBlocks.PODZOL_LAYER, new Item.Settings());
        POLISHED_ANDESITE_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_ANDESITE_LAYER, new Item.Settings());
        POLISHED_BASALT_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_BASALT_LAYER, new Item.Settings());
        POLISHED_BLACKSTONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_BLACKSTONE_BRICK_LAYER, new Item.Settings());
        POLISHED_BLACKSTONE_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_BLACKSTONE_LAYER, new Item.Settings());
        POLISHED_DEEPSLATE_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_DEEPSLATE_LAYER, new Item.Settings());
        POLISHED_DIORITE_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_DIORITE_LAYER, new Item.Settings());
        POLISHED_GRANITE_LAYER = new BlockItem(MoreBlockBlocks.POLISHED_GRANITE_LAYER, new Item.Settings());
        PRISMARINE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.PRISMARINE_BRICK_LAYER, new Item.Settings());
        PRISMARINE_LAYER = new BlockItem(MoreBlockBlocks.PRISMARINE_LAYER, new Item.Settings());
        PURPLE_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_CONCRETE_LAYER, new Item.Settings());
        PURPLE_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_CONCRETE_POWDER_LAYER, new Item.Settings());
        PURPLE_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        PURPLE_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_STAINED_GLASS_LAYER, new Item.Settings());
        PURPLE_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_TERRACOTTA_LAYER, new Item.Settings());
        PURPLE_WOOL_LAYER = new BlockItem(MoreBlockBlocks.PURPLE_WOOL_LAYER, new Item.Settings());
        PURPUR_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.PURPUR_BLOCK_LAYER, new Item.Settings());
        PURPUR_PILLAR_LAYER = new BlockItem(MoreBlockBlocks.PURPUR_PILLAR_LAYER, new Item.Settings());
        QUARTZ_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.QUARTZ_BLOCK_LAYER, new Item.Settings());
        QUARTZ_BRICK_LAYER = new BlockItem(MoreBlockBlocks.QUARTZ_BRICK_LAYER, new Item.Settings());
        QUARTZ_PILLAR_LAYER = new BlockItem(MoreBlockBlocks.QUARTZ_PILLAR_LAYER, new Item.Settings());
        RAW_COPPER_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.RAW_COPPER_BLOCK_LAYER, new Item.Settings());
        RAW_GOLD_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.RAW_GOLD_BLOCK_LAYER, new Item.Settings());
        RAW_IRON_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.RAW_IRON_BLOCK_LAYER, new Item.Settings());
        REDSTONE_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.REDSTONE_BLOCK_LAYER, new Item.Settings());
        REDSTONE_ORE_LAYER = new BlockItem(MoreBlockBlocks.REDSTONE_ORE_LAYER, new Item.Settings());
        RED_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.RED_CONCRETE_LAYER, new Item.Settings());
        RED_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.RED_CONCRETE_POWDER_LAYER, new Item.Settings());
        RED_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.RED_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        RED_NETHER_BRICK_LAYER = new BlockItem(MoreBlockBlocks.RED_NETHER_BRICK_LAYER, new Item.Settings());
        RED_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.RED_SANDSTONE_LAYER, new Item.Settings());
        RED_SAND_LAYER = new BlockItem(MoreBlockBlocks.RED_SAND_LAYER, new Item.Settings());
        RED_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.RED_STAINED_GLASS_LAYER, new Item.Settings());
        RED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.RED_TERRACOTTA_LAYER, new Item.Settings());
        RED_WOOL_LAYER = new BlockItem(MoreBlockBlocks.RED_WOOL_LAYER, new Item.Settings());
        REINFORCED_DEEPSLATE_LAYER = new BlockItem(MoreBlockBlocks.REINFORCED_DEEPSLATE_LAYER, new Item.Settings());
        ROOTED_DIRT_LAYER = new BlockItem(MoreBlockBlocks.ROOTED_DIRT_LAYER, new Item.Settings());
        SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.SANDSTONE_LAYER, new Item.Settings());
        SAND_LAYER = new BlockItem(MoreBlockBlocks.SAND_LAYER, new Item.Settings());
        SCULK_CATALYST_LAYER = new BlockItem(MoreBlockBlocks.SCULK_CATALYST_LAYER, new Item.Settings());
        SCULK_LAYER = new BlockItem(MoreBlockBlocks.SCULK_LAYER, new Item.Settings());
        SHROOMLIGHT_LAYER = new BlockItem(MoreBlockBlocks.SHROOMLIGHT_LAYER, new Item.Settings());
        SLIME_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.SLIME_BLOCK_LAYER, new Item.Settings());
        SMOOTH_BASALT_LAYER = new BlockItem(MoreBlockBlocks.SMOOTH_BASALT_LAYER, new Item.Settings());
        SMOOTH_QUARTZ_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.SMOOTH_QUARTZ_BLOCK_LAYER, new Item.Settings());
        SMOOTH_RED_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.SMOOTH_RED_SANDSTONE_LAYER, new Item.Settings());
        SMOOTH_SANDSTONE_LAYER = new BlockItem(MoreBlockBlocks.SMOOTH_SANDSTONE_LAYER, new Item.Settings());
        SMOOTH_STONE_LAYER = new BlockItem(MoreBlockBlocks.SMOOTH_STONE_LAYER, new Item.Settings());
        SOUL_SAND_LAYER = new BlockItem(MoreBlockBlocks.SOUL_SAND_LAYER, new Item.Settings());
        SOUL_SOIL_LAYER = new BlockItem(MoreBlockBlocks.SOUL_SOIL_LAYER, new Item.Settings());
        SPONGE_LAYER = new BlockItem(MoreBlockBlocks.SPONGE_LAYER, new Item.Settings());
        SPRUCE_LAYER = new BlockItem(MoreBlockBlocks.SPRUCE_LAYER, new Item.Settings());
        SPRUCE_LEAVES_LAYER = new BlockItem(MoreBlockBlocks.SPRUCE_LEAVES_LAYER, new Item.Settings());
        SPRUCE_LOG_LAYER = new BlockItem(MoreBlockBlocks.SPRUCE_LOG_LAYER, new Item.Settings());
        SPRUCE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.SPRUCE_WOOD_LAYER, new Item.Settings());
        STONE_BRICK_LAYER = new BlockItem(MoreBlockBlocks.STONE_BRICK_LAYER, new Item.Settings());
        STONE_LAYER = new BlockItem(MoreBlockBlocks.STONE_LAYER, new Item.Settings());
        STRIPPED_ACACIA_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_ACACIA_LOG_LAYER, new Item.Settings());
        STRIPPED_ACACIA_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_ACACIA_WOOD_LAYER, new Item.Settings());
        STRIPPED_BAMBOO_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_BAMBOO_BLOCK_LAYER, new Item.Settings());
        STRIPPED_BIRCH_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_BIRCH_LOG_LAYER, new Item.Settings());
        STRIPPED_BIRCH_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_BIRCH_WOOD_LAYER, new Item.Settings());
        STRIPPED_CHERRY_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_CHERRY_LOG_LAYER, new Item.Settings());
        STRIPPED_CHERRY_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_CHERRY_WOOD_LAYER, new Item.Settings());
        STRIPPED_CRIMSON_HYPHAE_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_CRIMSON_HYPHAE_LAYER, new Item.Settings());
        STRIPPED_CRIMSON_STEM_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_CRIMSON_STEM_LAYER, new Item.Settings());
        STRIPPED_DARK_OAK_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_DARK_OAK_LOG_LAYER, new Item.Settings());
        STRIPPED_DARK_OAK_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_DARK_OAK_WOOD_LAYER, new Item.Settings());
        STRIPPED_JUNGLE_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_JUNGLE_LOG_LAYER, new Item.Settings());
        STRIPPED_JUNGLE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_JUNGLE_WOOD_LAYER, new Item.Settings());
        STRIPPED_MANGROVE_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_MANGROVE_LOG_LAYER, new Item.Settings());
        STRIPPED_MANGROVE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_MANGROVE_WOOD_LAYER, new Item.Settings());
        STRIPPED_OAK_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_OAK_LOG_LAYER, new Item.Settings());
        STRIPPED_OAK_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_OAK_WOOD_LAYER, new Item.Settings());
        STRIPPED_SPRUCE_LOG_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_SPRUCE_LOG_LAYER, new Item.Settings());
        STRIPPED_SPRUCE_WOOD_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_SPRUCE_WOOD_LAYER, new Item.Settings());
        STRIPPED_WARPED_HYPHAE_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_WARPED_HYPHAE_LAYER, new Item.Settings());
        STRIPPED_WARPED_STEM_LAYER = new BlockItem(MoreBlockBlocks.STRIPPED_WARPED_STEM_LAYER, new Item.Settings());
        TARGET_LAYER = new BlockItem(MoreBlockBlocks.TARGET_LAYER, new Item.Settings());
        TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.TERRACOTTA_LAYER, new Item.Settings());
        TINTED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.TINTED_GLASS_LAYER, new Item.Settings());
        TUBE_CORAL_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.TUBE_CORAL_BLOCK_LAYER, new Item.Settings());
        TUFF_LAYER = new BlockItem(MoreBlockBlocks.TUFF_LAYER, new Item.Settings());
        VERDANT_FROGLIGHT_LAYER = new BlockItem(MoreBlockBlocks.VERDANT_FROGLIGHT_LAYER, new Item.Settings());
        WARPED_HYPHAE_LAYER = new BlockItem(MoreBlockBlocks.WARPED_HYPHAE_LAYER, new Item.Settings());
        WARPED_LAYER = new BlockItem(MoreBlockBlocks.WARPED_LAYER, new Item.Settings());
        WARPED_NYLIUM_LAYER = new BlockItem(MoreBlockBlocks.WARPED_NYLIUM_LAYER, new Item.Settings());
        WARPED_STEM_LAYER = new BlockItem(MoreBlockBlocks.WARPED_STEM_LAYER, new Item.Settings());
        WARPED_WART_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.WARPED_WART_BLOCK_LAYER, new Item.Settings());
        WAXED_COPPER_BLOCK_LAYER = new BlockItem(MoreBlockBlocks.WAXED_COPPER_BLOCK_LAYER, new Item.Settings());
        WAXED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WAXED_CUT_COPPER_LAYER, new Item.Settings());
        WAXED_EXPOSED_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WAXED_EXPOSED_COPPER_LAYER, new Item.Settings());
        WAXED_EXPOSED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WAXED_EXPOSED_CUT_COPPER_LAYER, new Item.Settings());
        WAXED_WEATHERED_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WAXED_WEATHERED_COPPER_LAYER, new Item.Settings());
        WAXED_WEATHERED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WAXED_WEATHERED_CUT_COPPER_LAYER, new Item.Settings());
        WEATHERED_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WEATHERED_COPPER_LAYER, new Item.Settings());
        WEATHERED_CUT_COPPER_LAYER = new BlockItem(MoreBlockBlocks.WEATHERED_CUT_COPPER_LAYER, new Item.Settings());
        WET_SPONGE_LAYER = new BlockItem(MoreBlockBlocks.WET_SPONGE_LAYER, new Item.Settings());
        WHITE_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.WHITE_CONCRETE_LAYER, new Item.Settings());
        WHITE_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.WHITE_CONCRETE_POWDER_LAYER, new Item.Settings());
        WHITE_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.WHITE_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        WHITE_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.WHITE_STAINED_GLASS_LAYER, new Item.Settings());
        WHITE_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.WHITE_TERRACOTTA_LAYER, new Item.Settings());
        WHITE_WOOL_LAYER = new BlockItem(MoreBlockBlocks.WHITE_WOOL_LAYER, new Item.Settings());
        YELLOW_CONCRETE_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_CONCRETE_LAYER, new Item.Settings());
        YELLOW_CONCRETE_POWDER_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_CONCRETE_POWDER_LAYER, new Item.Settings());
        YELLOW_GLAZED_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_GLAZED_TERRACOTTA_LAYER, new Item.Settings());
        YELLOW_STAINED_GLASS_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_STAINED_GLASS_LAYER, new Item.Settings());
        YELLOW_TERRACOTTA_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_TERRACOTTA_LAYER, new Item.Settings());
        YELLOW_WOOL_LAYER = new BlockItem(MoreBlockBlocks.YELLOW_WOOL_LAYER, new Item.Settings());
    }
}
